### ISSUE TITLE
Documentation: create service principal using service principal auth

### ISSUE THREAD

**Issue by cmeyertons** [terraform-providers/terraform-provider-azuread#10]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [service principal resource documentation](https://www.terraform.io/docs/providers/azurerm/r/azuread_service_principal.html) states:
```
NOTE: If you're authenticating using a Service Principal then it must have permissions to both Read and write all applications and Sign in and read user profile within the Windows Azure Active Directory API.
```

Yet there's no documentation on really "how" to do that -- it would be awesome if you included this case on [Authenticating via Service Principal](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html) as its directly related to that documentation.

Then the [service principal resource documentation](https://www.terraform.io/docs/providers/azurerm/r/azuread_service_principal.html) could have a link pointing to that section in the docs.

Do you have a quick answer using the Azure CLI as to how to add the necessary roles?  I can only work on this project a couple hours a day and performing `az login` everytime has gotten annoying!

### Affected Resource(s)

* azurerm_azuread_service_principal*

**Comment by katbyte** [comment]
Hi @cmeyertons,

The correct documentation on how to correctly configure a service principal is actual [here](url). I believe it was added after you opened this ticket, and is still not on the sidebar! i've opened #84 that fixes this as well as adding a link in the `azuread_service_principal` documentation 🙂 Hopefully this will clear things up for users in the future.

**Comment by cmeyertons** [comment]
@katbyte the `here` link didn't work, but i think i found it [here](https://www.terraform.io/docs/providers/azuread/auth/service_principal_configuration.html)

Looks great, thanks so much!
