### ISSUE TITLE
Provider "azuread" v0.4.0 is not compatible with Terraform 0.12.1.

### ISSUE THREAD

**Issue by joakimhellum-in** [terraform-providers/terraform-provider-azuread#101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v0.12.1
+ provider.azuread v0.4.0
```
### Affected Resource(s)

N/A

### Terraform Configuration Files

```hcl
provider "azuread" {
  version = "=0.4.0"
}
```

### Debug Output

```
Initializing provider plugins...
- Checking for available provider plugins...
2019/06/07 01:16:18 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/azuread/versions"

Provider "azuread" v0.4.0 is not compatible with Terraform 0.12.1.

Provider version 0.3.1 is the latest compatible version. Select it with
the following constraint:

    version = "~> 0.3"

Terraform checked all of the plugin versions matching the given constraint:
    =0.4.0

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.

Alternatively, upgrade to the latest version of Terraform for compatibility with newer provider releases.


Error: incompatible provider version
```

### Panic Output

N/A

### Expected Behavior

Provider version v0.4.0 should be compatible with Terraform v0.12

### Actual Behavior

Terraform fetches versions from registry, but the information is incorrect ref. https://registry.terraform.io/v1/providers/-/azuread/versions

```json
        {
            "version": "0.4.0",
            "protocols": [
                "4.0"
            ],
```
("5.0" is missing from list)

### Steps to Reproduce

1. `terraform init`

### References

* #0000

**Comment by katbyte** [comment]
Many apologies! during the release process it was not marked as .12 compatible (even though it is!)

This should hopefully be rectified within the next 12 hours 🤞

**Comment by joakimhellum-in** [comment]
I tried running `terraform init` using Terraform v0.12 some time ago and it downloaded azuread 0.4.0 provider successfully, so will close this issue. Thanks!
