### ISSUE TITLE
azuread_application_password object_id argument vs documentation

### ISSUE THREAD

**Issue by mjiderhamn** [terraform-providers/terraform-provider-azuread#106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [documentation for resource `azuread_application_password`](https://www.terraform.io/docs/providers/azuread/r/application_password.html) makes reference to `object_id`. The [provider itself however uses `application_id`](https://github.com/terraform-providers/terraform-provider-azuread/blob/master/azuread/resource_application_password.go#L33).

The actual value should be [the `object_id` of the `azuread_application`](https://www.terraform.io/docs/providers/azuread/r/application.html#object_id) rather than the `application_id`, so it is probably more correct to update the code than the documentation.

### New or Affected Resource(s)

* `azuread_application_password`

**Comment by katbyte** [comment]
Thanks for brining this to light @mjiderhamn, that is a very good point.

I have opened #107 to change the name of that property to `application__object_id` to make it explicit what is being asked for given that applications have an `application_id` property.
