### ISSUE TITLE
Service Principal passwords are stored as plaintext

### ISSUE THREAD

**Issue by monkey-jeff** [terraform-providers/terraform-provider-azuread#11]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using resource "azurerm_azuread_service_principal_password" the password that you create is saved in plaintext when stored in the statefile.  Since you never want to get that password out of the statefile to use it would be better to hash it to prevent people from getting sensitive information from the state.

### New or Affected Resource(s)

* azurerm_azuread_service_principal_password

### References

#2402 Would address and fix this problem

**Comment by katbyte** [comment]
Hi @monkey-jeff,

This applies to all sensitive data across all providers thus it is not really specific to AzureRM or AzureAD. Please see the [terraform documentation](https://www.terraform.io/docs/state/sensitive-data.html) for more information on how terraform handles sensitive data.

Closing in favour of the overreaching [terraform issue](https://github.com/hashicorp/terraform/issues/9556)
