### ISSUE TITLE
Error when setting tags property on azuread_service_principal

### ISSUE THREAD

**Issue by OwenGr** [terraform-providers/terraform-provider-azuread#122]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.12.4
+ provider.azuread v0.4.0
+ provider.azurerm v1.31.0
+ provider.random v2.1.2

### Affected Resource(s)

* `azuread_service_principal`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12"
  backend "azurerm" {
    storage_account_name = "testremstatestg"
    container_name       = "tfstate"
    key                  = "test.tfstate"
  }
}

locals {
  tags = {
    PointOfContact = "test@test.com"
    AppId          = "rgrptest"
    ExpiresOn      = "31-Jul-2020"
  }
}

resource "azurerm_resource_group" "rgrp" {
  name     = "TestRgrp"
  location = "WestUS2"

  tags = local.tags
}

resource "azuread_application" "app" {
  name                       = "TestSP"
  available_to_other_tenants = false
}

resource "azuread_service_principal" "sp" {
  application_id = azuread_application.app.application_id

  tags = local.tags # <- doesn't accept local.tags
}
```

### Debug Output

https://gist.github.com/OwenGr/b3b85e87b065e7dbf3a7147248ea98e3

### Expected Behavior

Tags set appropriately.

### Actual Behavior

```
Error: Incorrect attribute value type

  on terraform.tf line 46, in resource "azuread_service_principal" "sp":
  46:   tags = local.tags

Inappropriate value for attribute "tags": set of string required.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nope

### References

Note that the same `tags = local.tags` works fine in the resource group creation.

**Comment by matsest** [comment]
The definition for service principals in AzureAd is [different ](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta) than for resource groups in Azure.

As the error notes, you need a set of strings as tags. As such, a valid form would be:

```
locals {
  tags = [
   "test@test.com",
    "rgrptest",
    "31-Jul-2020",
  ]
}
```

**Comment by OwenGr** [comment]
Ah. Gotcha. My bad.
