### ISSUE TITLE
[0.5.0] azuread_application_password 'conflicts with application_id' error

### ISSUE THREAD

**Issue by dmeenhuis** [terraform-providers/terraform-provider-azuread#126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.12.5
+ provider.azuread v0.5.0
+ provider.azurerm v1.31.0

### Affected Resource(s)

* `azuread_application_password`

### Terraform Configuration Files

```terraform
resource "azuread_application" "app" {
   /* omitted for brevity */
}

resource "azuread_application_password" "app_password" {
  application_id        = azuread_application.app.id
  value                 = "some-password"
  end_date              = "2299-01-01T00:00:00Z"
}
```

### Debug Output

https://gist.github.com/dmeenhuis/3b9b0a84354ec3d5a2f0163bf3a239b0

### Expected Behavior

After updating the Azure AD provider to version `0.5.0`, my existing application password resources suddenly stopped working. I suspect it has something to do with the deprecation of using `application_id` changed by https://github.com/terraform-providers/terraform-provider-azuread/pull/107.

### Actual Behavior

When I run `terraform plan` now however, I'm getting the following error:

```
Error: "application_id": conflicts with application_id

  on ../modules/azure-ad-app/main.tf line 37, in resource "azuread_application_password" "app_password":
  37: resource "azuread_application_password" "app_password" {
```

I've tried updating `application_id` in my resource to `application_object_id`, but that gives the same type of error. When I remove the `application_id` entirely, it seems to work correctly, which I find strange, since either is a required value. Could it have something to do with the fact that the resource is already created?

### Steps to Reproduce

1. Use version `0.4.0` of the Azure AD provider
2. Create an application and application password using Terraform
3. Update the provider to `0.5.0`
4. Run `terraform plan` again

### Important Factoids

None

### References

* #0000

**Comment by mikkoc** [comment]
Exact same thing here. Had to downgrade to 0.4.0

**Comment by katbyte** [comment]
Hi @dmeenhuis, @mikkoc,

Sorry that latest release broke your workflow. I have taken a look and opened #129 that should resolve this (and should be released within the hour).

**Comment by dmeenhuis** [comment]
Yes that seems to fix the issue. Thanks for resolving this so quickly!
