### ISSUE TITLE
Support creation of Azure AD Application with "Native" application type

### ISSUE THREAD

**Issue by shopskyi** [terraform-providers/terraform-provider-azuread#13]
Please add ability to create azuread_application resource with application type "Native". By default,  azuread_application resource is being created with application type is "Web app / API"

For example: 

resource "azuread_application" "app" {
    name = "app"
    **type = "native"**
}

fixes #74

**Comment by sshkel** [comment]
@tombuildsstuff if you have any thoughts on this one would appreciate it. Tagged you because you were the last one to commit to this repo :)

**Comment by katbyte** [comment]
Hi @sshkel,

This looks like a good start to me. Do we need to clear the homepage? How does the CLI handle the homepage, does it allow an empty one to be set or does it simply ignore the property in the long run?

**Comment by sshkel** [comment]
Hi @katbyte, thanks for volunteering to help out ^_^
When I run it through cli with minimal args, it sets homepage to null. E.g.
`az ad app create --display-name yolo-cli --native-app`
Though cli allows me to provide homepage for native app.
`az ad app create --display-name yolo-cli --native-app --homepage "homepageio"`
So I suspect it's not a requirement? That's the part I wanted to confirm and it would be nice to have a consistent behaviour between cli and the terraform module.
Empty value for homepage seems like  not a valid thing in general
Doing this fails
```
az ad app create --display-name yolo-cli --native-app --homepage ""
Invalid value specified for property 'homepage' of resource 'Application'.
```

**Comment by katbyte** [comment]
Hmm, so it sounds like the CLI is passing nil, and your saying if you make homepage optional and try:

```go
	if v, ok := d.GetOk("homepage"); ok {
		properties. Homepage = expandADApplicationHomepage(d, name)
	}
```

doesn't it work?

**Comment by sshkel** [comment]
ahhh, no, you are right we can totally do that. Looks like current application module diverged from what cli does. With cli if you don't provide a homepage it sets it to null, while terraform module uses expandADApplicationHomepage that helpfully replaces it to https:// + name, if homepage not defined.
Thanks @katbyte, appreciate you holding my hand through this 😄 

I will cleanup my code a little bit and get something for a PR.

**Comment by katbyte** [comment]
Happy to help @sshkel 🙂 look forward to the PR

**Comment by sshkel** [comment]
@dominik-lekse makes sense, happy to refactor things if anyone else doesn't have strong objections.

**Comment by jjgrayston** [comment]
how's this coming along?

**Comment by sshkel** [comment]
@jjgrayston there is a PR currently in review

**Comment by praneetloke** [comment]
@sshkel just wondering if you think the linked PR would be merged soon? Thank you so much for doing the work on this! This is an essential feature for being able to manage AAD apps.

**Comment by sshkel** [comment]
@praneetloke I am waiting for @katbyte to do a final review, any further tweaks should be minor and quick.
You are welcome, friend :)
