### ISSUE TITLE
Documentation: azuread_service_principal references use of tags

### ISSUE THREAD

**Issue by arcotek-ltd** [terraform-providers/terraform-provider-azuread#142]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread__service_principal`

### Terraform Configuration Files

```hcl
resource "azuread_service_principal" "pool" {
  count                         = var.n
  application_id                = var.aad_application_id
  app_role_assignment_required  = var.app_role_assignment_required
  tags = {
    purpose = "test"
  }
}
```
In your [documentation](https://www.terraform.io/docs/providers/azuread/r/service_principal.html#tags), you refer to the tags attribute. Are you sure tags are available for a service principal?

I get the error:
```hcl
Error: Missing required argument

  on main.tf line 95, in module "aad_service_principal":
  95: module "aad_service_principal" {

The argument "tags" is required, but no definition was found.
```

If I am correct, that error message along with your documentation is very misleading.

* #0000

**Comment by matsest** [comment]
See #122

**Comment by katbyte** [comment]
Hi @arcotek-ltd,

The error message is by terraform so theres not much we can do but the updated documentation shows the correct way to apply tags:
```
tags = ["example", "tags", "here"]
```

as such i am going to close this
