### ISSUE TITLE
Add support for optionalClaims in azuread_application

### ISSUE THREAD

**Issue by rcurd** [terraform-providers/terraform-provider-azuread#145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to set the optionalClaims field in Azure AD Application Registrations via Terraform. Currently this does not appear to be supported.

### New or Affected Resource(s)

azuread_application

* azuread_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims

* #0000

**Comment by katbyte** [comment]
(maybe good first issue)

supported by the SDK with `OptionalClaims` property

**Comment by RavulaChetan** [comment]
Any new update on this?

**Comment by manicminer** [comment]
This has been added with #261 and we'll include it in the next release of the provider.
