### ISSUE TITLE
Service Principal for the AKS is missing Microsoft.Network/virtualNetworks/subnets/join/action

### ISSUE THREAD

**Issue by florianrusch** [terraform-providers/terraform-provider-azuread#146]
I've deployed a AKS with terraform and created for this the following SP:
```hcl
resource "azuread_application" "this" {
  name                       = "${var.cluster_name}"
  homepage                   = "https://${var.cluster_name}"
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
}

resource "azuread_service_principal" "this" {
  application_id = "${azuread_application.this.application_id}"
}

resource "azuread_service_principal_password" "this" {
  service_principal_id = "${azuread_service_principal.this.id}"
  value                = "${var.client_secret}"
  end_date             = "${var.end_date}"
}
```

Now I'm trying to deploy also with terraform and the helm provider a nginx-ingress controller. This also works as aspected. But when service from type loadbalancer is created* it comes to the following error:

```
Error creating load balancer (will retry): failed to ensure load balancer for service default/nginx-ingress-controller: ensure(default/nginx-ingress-controller): backendPoolID(/subscriptions/xxx/resourceGroups/MC_playground_fr-test-cluster_westeurope/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes) - failed to ensure host in pool: 

"network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. 

Status=403 Code=\"LinkedAuthorizationFailed\" Message=\"The client '9c80022c-ecb7-46bd-xxx' with object id '9c80022c-ecb7-46bd-xxx' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/xxx/resourceGroups/MC_playground_fr-test-cluster_westeurope/providers/Microsoft.Network/networkInterfaces/aks-default-33372814-nic-0'; however, it does not have permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) '/subscriptions/xxx/resourceGroups/playground/providers/Microsoft.Network/virtualNetworks/fr-test-vn/subnets/fr-test-subnet' or the linked scope(s) are invalid.\""
```

The interesting part is the message `it does not have permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) '/subscriptions/xxx/resourceGroups/playground/providers/Microsoft.Network/virtualNetworks/fr-test-vn/subnets/fr-test-subnet'` which means for me, if I'm right, that the SP doens't has the right permissions or? But I've compared it with an existing AKS (compared the manifests in the azure portal) which was deployed manually in the azure portal and there were no difference except the field `passwordCredentials` which is empty by the SP which I've deployed with terraform.

My resources in azure are looking like this:
- 1. Resource Group:
    - AKS
    - VN
        - Subnet 1 (Where I assign the AKS to)
        - Subnet 2
- 2. Resource Group: (Created by AKS)
    - K8s Nodes (VM Instances, Create by AKS)
    - Network interfaces (Create by AKS)
    - Network security group (Create by AKS)
    - LoadBalancer (Create by AKS)
    - Public IP address (Create by AKS or LB?)
    - ...

Does someone knows anything which can help me fixing this issue?

**Comment by tiwood** [comment]
Your service principal is missing the required Azure RBAC permissions/roles. If you create a service principal for AKS in the portal, Azure is assigning the `Network contributor` role to the principal.

To do the same with Terraform you can add:

```hcl
resource "azurerm_role_assignment" "foo" {
  scope                = "" #add your scope here (like your subscription id or the AKS resource group id
  role_definition_name = "Network Contributor"
  principal_id         = azuread_service_principal.this.application_id
}
```

**Comment by florianrusch** [comment]
@tiwood thanks for your answer! That explains a lot.
Just one question. Does this role assignment need to be for the aks resource group where the nodes and the load balancer lives, or to the resource group, where the virtual network lives? 🤔 To the virtual network resource group or?

**Comment by MatejMalicek** [comment]
I came across this error message this afternoon when installing AAD Pod Identity on a new Dev cluster. 

From my testing, it looks like the "Network Contributor" role only needs to be assigned over the network resources that will be used by the Service Principal, which would generally be the subnet in which the AKS cluster was provisioned. Whilst you could assign the role over an entire RG, this would have security implications, as it would allow the Service Principal to exercise Network Contributor permissions over [b]any resource[/b] within the RG.

The error message actually tells you the correct scope of the role to assign, namely in your case:
```
/subscriptions/xxx/resourceGroups/playground/providers/Microsoft.Network/virtualNetworks/fr-test-vn/subnets/fr-test-subnet
```
(Obviously replace with whatever actually showed up in your logs.)

This would assign the least privilege required and seemed to work for AAD Pod Identity purposes, though I haven't tested with Terraform or creating a load balancer (am about to do the latter shortly).
