### ISSUE TITLE
Set owners on azuread_application resources

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azuread#153]
This is a duplicate of #46 which appears to be closed and implemented, but does not work with the latest release (0.6.0).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v0.12.6
+ provider.azuread v0.6.0
```

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "test" {
  name                       = "app-owner-test"
  owners                      = "${var.app_owner}"
  available_to_other_tenants = false
}
```

### Expected Behavior

Assign owners to the application registration in Azure.

### Actual Behavior

```
Error: Unsupported argument

  on main.tf line 10, in resource "azuread_application" "test":
  10:   owners                      = "${var.app_owner}"

An argument named "owners" is not expected here.
```

### Steps to Reproduce

1. `terraform plan`

### References

* #46

**Comment by danieladams456** [comment]
Just to clarify, are you referring to the **Owners** tab on **App registrations** blade in the console or the **Owners** tab on **Enterprise applications** blade?

For me, the owner under app registrations seems to be set when [authenticating with the CLI](https://www.terraform.io/docs/providers/azuread/auth/azure_cli.html).  However there is no owner set under Enterprise Applications.  I need to set the owner there to be able to assign roles to show up in the access token.

When I create an app in the Azure portal, I am automatically set as owner in both places.  Creating via terraform the Enterprise applications owners **Add** button is grayed out.  Is there any way to do that via the CLI as a workaround?  Output from `az ad app owner list --id $ID` is exactly the same for console vs Terraform, so I am assuming that is referring to the app registration owner, but I need to modify the other.
Thanks!

**Comment by katbyte** [comment]
There is a additional function in the SDK that might be relevent here:
```
func (client ApplicationsClient) AddOwner(ctx context.Context, applicationObjectID string, parameters AddOwnerParameters) (result autorest.Response, err error) {
```

**Comment by mbrancato** [comment]
Thanks @katbyte and @tracypholmes !

**Comment by danieladams456** [comment]
For anyone's future reference, I found what my issue was.  I needed to create a `azuread_service_principal` resource which would set me as the owner.  What was confusing was there seemed to be a service principal created by default, it was just one I didn't have access to.
