### ISSUE TITLE
azuread_application: support for setting oauth2 permissions (exposing APIs)

### ISSUE THREAD

**Issue by joakimhellum** [terraform-providers/terraform-provider-azuread#162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently Oauth2 permissions can be read for an application, but not set. It would be nice to add support for setting Oauth2 permissions as well (exposing APIs). However normally it's hard to maintain all Oauth2 permissions in Terraform, since some would be automatically created outside of Terraform. And such the suggestion is to add separate resource `azuread_application_oauth2_permission` for this.

I am happy to create a PR for this.

### New or Affected Resource(s)

* azuread_application_oauth2_permission

### Potential Terraform Configuration

```hcl
resource "azuread_application_oauth2_permission" "test" {
  application_object_id = azuread_application.main.object_id

  type = "User"

  admin_consent_description = "Allow access to example on behalf of the signed-in user."
  admin_consent_display_name = "Access example"

  user_consent_description = "Allow access to example on your behalf."
  user_consent_display_name = "Access example"

  value = "user_impersonation"
}
```

### References

* N/A

**Comment by rdbartram** [comment]
would love to see this happen. Why would it be its own resource though and not a block on azuread_application?

**Comment by joakimhellum-in** [comment]
@rdbartram You are right, there is no real justification for this currently. The reason for suggestion this initially is because i'm still not completely sure how to best manage the default ouath2 permission (`user_impersonation`) that is created for every application. 

> **oauth2Permissions: What actions does the app expose?**
>
> The oauth2Permissions collection publishes the list of things that client applications can do with your app—the scopes the app admits, mostly, but that comes into play only in case your app is a web API. If your app is a web application with a UX, the expectation is that browsers will request tokens for your app with the goal of signing in. That does not require any entry for web sign-on, the scenario considered in this chapter, so I thought of deferring coverage of this property until I get to exposing your own web API, but some of the concepts will come in handy sooner than that, so I’ll give you a bit of background now. Let’s take a closer look at the only entry in the oauth2Permissions collection for the sample application:
>
> {
    "adminConsentDescription": "Allow the application to access WebAppChapter5 on behalf of the
signed-in user.",
    "adminConsentDisplayName": "Access WebAppChapter5",
    "id": "00431d04-5334-4da6-8396-0e6f54631f10",
    "isEnabled": true,
    "type": "User",
    "userConsentDescription": "Allow the application to access WebAppChapter5 on your behalf.",
    "userConsentDisplayName": "Access WebAppChapter5",
    "value": "user_impersonation"
 }
>
> **Where does the default oauth2Permissions entry come from?**
>
> Answering this question requires a bit of history. For the way in which Azure AD is organized, a token obtained by a client for accessing a web API must contain at least a scope—which is, as you have seen, an action that the client obtains permissions to perform. An application representing a web API but not defining any scopes would be impossible to access because any token request would not have any scope to prompt consent for. That wasn’t always the case! This constraint was added a few months after Azure AD was released, creating a lot of confusion for developers who were now expected to manually add at least one oauth2Permission entry before being able to use their API. This also influenced all the walk-through and sample readme files at the time, making it necessary to add instructions on how to add that entry. I am happy to report that such manual steps are no longer necessary. Every Application is created with one default permission, user_impersonation, so that if you want to implement your app as a web API you don’t need any extra configuration step, and you can begin development right away. I am telling you all this because some of the walk-throughs from that phase are still around. Now you know that you don’t need to follow them to the letter on this.

Reference:
https://www.microsoftpressstore.com/articles/article.aspx?p=2473127

**Comment by rdbartram** [comment]
I think the user can just manage it as normal. If no oauthpermissions block then they are removed. If you user wants the default, they can add it themselves. I think as long as we document we should be ok. They should see in the plan if they are going to break something by deleting an existing permission. Its obviously a breaking change though and would probably end up in the version 2 of the provider. I don't mind the idea of a separate resource. it just becomes messy when you start using for_each

**Comment by joakimhellum-in** [comment]
@rdbartram: Thanks, I started working on your suggestion and will create PR for this within next 24 hours

**Comment by katbyte** [comment]
Hi @rdbartram & @joakimhellum-in,

Ideally we would want to allow the users to set this on the resource. If its marked as computed any created by azure out of band should be imported.

It may also make sense to have a separate resource, but i think we should support both much like we do with `azuread_group.members` and `azuread_group_member`.

There shouldn't be any need for a breaking change either.

**Comment by rdbartram** [comment]
the reason I say breaking change is because if we start deleting oauthpermissions because they haven't been defined then users will get pretty mad. Unless we say nothing means ignore and you have to define an empty block if you want to remove everything. I that case, I think a seperate resource is necessary to avoid confusion

**Comment by katbyte** [comment]
@rdbartram,

An optional computed block would be considered an empty value and not sent to the API so no users would be affected. If a user did want to clear all the permissions they would have to set it to an empty value:

```
  oauth_permissions = []
```

Each method has its purpose: ensure permissions are explicitly set to `X` vs add/ensure/remove a single permission.

**Comment by jorgecarleitao** [comment]
@joakimhellum, any updates on this? I am facing the same problem. If you have a incomplete PR let me know, and I will try to pick it from there.
