### ISSUE TITLE
Update azure-go-sdk to v23.0.0 (or later)

### ISSUE THREAD

**Issue by tiwood** [terraform-providers/terraform-provider-azuread#17]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have a resource provider for azuread_domain_services ready, but I need at least v23.0.0 of the azure-go-sdk to complete the implementation. (see https://github.com/Azure/azure-sdk-for-go/issues/3285)

**Comment by gerardaus** [comment]
Pull request #23 adds support for this feature.
