### ISSUE TITLE
azuread_group can create multiple groups with the same name

### ISSUE THREAD

**Issue by simongottschlag** [terraform-providers/terraform-provider-azuread#182]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
Terraform v0.12.16
+ provider.azuread v0.7.0
+ provider.azurerm v1.37.0
```

### Affected Resource(s)
* `azuread_group`

### Terraform Configuration Files
```hcl
resource "azuread_group" "aadGroupOwner" {
    name        = "aad-sec-u-dev-test-owner"
}
```

### Expected Behavior
Create a group if another one with the same name does not exists.

### Actual Behavior
Creates a group even if there's another one with the exact same name but different ID.

### Steps to Reproduce
Create the group in two different states.

### Important Factoids
When using Azure Portal, it's not possible to create a group if there's already an existing one.

**Comment by katbyte** [comment]
Hi @simongottschlag ,

Unfortunately the API works on GUID IDs. For now you can import the group via the app ID. In the future we could add a flag `check_name_availiblity`/`prevent_duplicate_names` which checks if the name is in use during creation and fails if it is.

**Comment by simongottschlag** [comment]
@katbyte thank you for the clarification! Not a big issue, as long as we don't loose our state. Looking forward to the new release!
