### ISSUE TITLE
data.azuread_service_principal: Support instantiating by client-id

### ISSUE THREAD

**Issue by erlacherl-city** [terraform-providers/terraform-provider-azuread#183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure supports querying service principals by client id:

```
az ad sp show --id e4223c08-d7c1-40a2-810a-d3f83e9b99d9
```

The [client id](https://www.terraform.io/docs/providers/azurerm/d/kubernetes_cluster.html#client_id) is also the only thing that the [`data.azure_kubernetes_cluster`](https://www.terraform.io/docs/providers/azurerm/d/kubernetes_cluster.html#client_id) data provider surfaces for the `service_principal`.

The `data.azuread_service_principal` data provider only supports using display name, object id, and application name.

This means, there is no way to get from an existing aks cluster to the object id of its service principal.

### New or Affected Resource(s)

* data.azuread_service_principal

### Potential Terraform Configuration

```hcl
data "azurerm_kubernetes_cluster" "my-cluster" {
    name = "myaks01"
    resource_group_name = data.azurerm_resource_group.somewhere.name
}

data "azuread_service_principal" "aks-sp" {
  client_id = data.azurem_kubernetes_cluster.my-cluster.service_principal[0].client_id
}
```

**Comment by manicminer** [comment]
Hi @erlacherl-city, thanks for requesting this! Good news - the `azuread_service_principal` data source happily supports this already. The attribute you want is `application_id`, which is just another name for `client_id`.

Additionally, we recently added support for the `application_id` (e.g. the client_id) argument to the `azuread_application` data source. This will be in our next release v0.11.0 - see https://github.com/terraform-providers/terraform-provider-azuread/pull/274
