### ISSUE TITLE
Support logoutUrl in azuread_application

### ISSUE THREAD

**Issue by scivm** [terraform-providers/terraform-provider-azuread#189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In azure ad sdk, logoutUrl is supported

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```resource "azuread_application" "test" {
    name = "test"
    logoutUrl = "/mylogout"
    ...
}
```

### References

https://docs.microsoft.com/en-gb/azure/active-directory/develop/reference-app-manifest

In azure-sdk-for-go/services/graphrbac/1.6/graphrbac/models.go, logoutUrl is supported.

**Comment by akingscote** [comment]
FYI as a workaround, im doing the following:
```
resource "null_resource" "add_logout_url" {
    provisioner "local-exec" {
        command = "az ad app update --id ${azuread_application.example.id} --set logoutUrl=https://mylogouturl"
    }
}
```
