### ISSUE TITLE
azuread_applcation identifier_uris only support https and http prefix

### ISSUE THREAD

**Issue by sjoby** [terraform-providers/terraform-provider-azuread#19]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "aws-cognito-xxx" {
  name                       = "aws-cognito-xxx"
  homepage                   = "https://localhost"
  identifier_uris            = ["urn:amazon:cognito:sp:us-east-1_YUXXXXX"]
  reply_urls                 = ["https://111.111.205.10:443/SAML20/SP"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
}
```

### Debug Output
Terraform output is:

```
Error: azuread_application.aws-cognito-xxx: "identifier_uris.0" url has no host: "urn:amazon:cognito:sp:us-east-1_YUXXXXX"
```

### Expected Behavior

identifier_uris and reply_urls should support URI and not only URL according to URI format
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier 

### Actual Behavior

Due to ValidateFunc: validate.URLIsHTTPOrHTTPS in https://github.com/terraform-providers/terraform-provider-azuread/blob/master/azuread/resource_application.go this is not supported for neither identifier_uris or reply_urls

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
Hi @sjoby,

I have removed validation and tried the identifier_uri you supplied:

```tf
resource "azuread_application" "test" {
  name                       = "acctest%s"
  identifier_uris            = ["urn:amazon:cognito:sp:us-east-1_YUXXXXX"]
  reply_urls                 = ["https://111.111.205.10:443/SAML20/SP"]
  available_to_other_tenants = true
}
`, i
```

and got the following response

```
[03:13:28] kt@snowbook:~/hashi/..3../terraform-providers/terraform-provider-azuread▸master$ make fmt; make testacc TEST=./azuread TESTARGS=-test.run=TestAccAzureADApplication_availableToOtherTenants
==> Fixing source code with gofmt...
gofmt -s -w ./azuread
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azuread -v -test.run=TestAccAzureADApplication_availableToOtherTenants -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azuread/version.ProviderVersion=acc"
=== RUN   TestAccAzureADApplication_availableToOtherTenants
=== PAUSE TestAccAzureADApplication_availableToOtherTenants
=== CONT  TestAccAzureADApplication_availableToOtherTenants
--- FAIL: TestAccAzureADApplication_availableToOtherTenants (0.61s)
    testing.go:538: Step 0 error: Error applying: 1 error(s) occurred:

        * azuread_application.test: 1 error(s) occurred:

        * azuread_application.test: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2019-01-22T11:15:15","message":{"lang":"en","value":"The URI scheme in property identifierUris is invalid or unsupported."},"requestId":"a6043fb0-6a5e-4802-893f-27e889a435db","values":[{"item":"PropertyName","value":"identifierUris"},{"item":"PropertyErrorCode","value":"InvalidUriScheme"}]}}]
FAIL
FAIL	github.com/terraform-providers/terraform-provider-azuread/azuread	1.942s
make: *** [testacc] Error 1
```

Do you have an example of the non http/https URL that the API will accept or how to coax the API validation to pass?

**Comment by sjoby** [comment]
Hi @katbyte  you are right this is an Azure limitation. If you import the Azure AD Application with a mainfest Identifer URIs with other prefixes than http / https prefix are supported by Azure. Through the Azure API it is not supported. This is not a terraform provider bug. You can close this. Thanks for looking into it. I will make sure I do more testing in the future. Thanks @sjoby

**Comment by tombuildsstuff** [comment]
hey @sjoby 

Thanks for getting back to us here - no worries, it's unfortunate the API doesn't allow this (but that this is supported for an imported application) - however should this become possible through the API in the future we'll take another look.

Thanks!
