### ISSUE TITLE
Move away from legacy Azure Active Directory Graph to new Microsoft Graph

### ISSUE THREAD

**Issue by drdamour** [terraform-providers/terraform-provider-azuread#193]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider currently uses the `Azure Active Directory Graph` which has been marked as legacy
![image](https://user-images.githubusercontent.com/1514496/71266878-8c5e7d00-2306-11ea-866f-2f85834b3238.png)

My DevOps team doesn't like granting legacy permissions, suggest moving to the newer api's and permissions. This could be done in a backwards compatible way at first either with provider switch or through code that trys the first API and fallsback to the second.

### New or Affected Resource(s)

probably a lot, but at least 

* azuread_group
* azuread_user
* azuread_users

### Potential Terraform Configuration

```hcl
provider "azuread" {
  version = "=0.3.0"
  preferred_graph_api = "microsoft-graph" #or aad-graph
}
```

### References
none

**Comment by sbkg0002** [comment]
This would be great!

**Comment by manicminer** [comment]
Thanks for raising this! The Azure SDK for Go currently only supports the Azure AD Graph API (graph.windows.net) and not Microsoft Graph (graph.microsoft.com). As you correctly state, the former is deprecated and over time more functionality is becoming available in the MS Graph API.

This has been raised upstream, see https://github.com/Azure/azure-sdk-for-go/issues/7352

**Comment by dominik-lekse** [comment]
Can we pin this issue since it seems to affect a notable number of improvements of the provider?

Also, because an official Go SDK for the new Microsoft Graph API is not available at the time of writing, it effectively blocks the support for features in the provider which are only available in the Microsoft Graph API and not in the legacy Azure AD Graph API.

Are people from Microsoft involved in the improvement/development of this provider as it is the case for the azurerm provider?

**Comment by manicminer** [comment]
We have a roadmap for the provider which centers around building out MS Graph support, and we are actively tracking issues that directly depend on that support. I don't believe it makes sense to pin this issue as it's already readily searchable and there isn't any reference discussion here.

**Comment by rrey** [comment]
Is it possible to have an update on this ? We are currently forced to use another tool to handle the group creation because the Legacy API does not have enough fine grained permissions for our security team taste...

**Comment by manicminer** [comment]
Hello to all watching this thread. There's now a [pinned issue](https://github.com/terraform-providers/terraform-provider-azuread/issues/323) explaining our plan and progress towards MS Graph support. I'm going to close this issue in favor of that one, please feel free to raise comments or questions there. Thanks!
