### ISSUE TITLE
What is the max length the service principal password value can take?

### ISSUE THREAD

**Issue by yanni1994** [terraform-providers/terraform-provider-azuread#195]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by katbyte** [comment]
Hey @yanni1994, it looks like the `Encrypted secret cannot be empty and can be at most 1024 bytes.` which seems to work out to around 863 characters. I've opened #228 to add validation to enforce this.
