### ISSUE TITLE
duplicate azuread_application resources are created when redeploying

### ISSUE THREAD

**Issue by diirib** [terraform-providers/terraform-provider-azuread#200]
When creating an azuread_application resource, we define the display name. If we try to redeploy the same resource, since the applicationId is created automatically and is different from the one deployed the first time, terraform creates a new application with the same name but a different applicationId.

I would expect to at least have a parameter to specify if I want a new resource to be created or I'm just redeploying. 

Is the applicationId the only way to check if there's an existing application?

**Comment by katbyte** [comment]
Hi @diirib,

Unfortunately the API works on GUID IDs. For now you can import the application via the app ID. In the future we could add a flag `check_name_availiblity`/`prevent_duplicate_names` which checks if the name is in use during creation and fails if it is.
