### ISSUE TITLE
Permissions to use data source azuread_service_principal

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azuread#205]
Are specific AAD permissions required to use `azuread_service_principal` as a data source only? I'm thinking it might be good to add these to documentation.

I've tried `Directory.Read.All` under Microsoft Graph, but according to [this](https://github.com/terraform-providers/terraform-provider-azuread/issues/131) issue, it seems maybe this client is using the Legacy AAD Graph API? if, so, is there an issue tracking a move to the supported Microsoft Graph API?

**Comment by mbrancato** [comment]
I was able to confirm it seems that the provider seems to be using the legacy API, at least for this resource. It seems moving to the Graph API would be a breaking change, is it on the roadmap?

**Comment by katbyte** [comment]
hey @mbrancato, glad you figured it out and its not currently on the roadmap. there is an issue relating to upgrading to the new api #193 so i am going to close this and keep discussion there. Thanks!
