### ISSUE TITLE
identifier_uris not persistently set 

### ISSUE THREAD

**Issue by MarkDordoy** [terraform-providers/terraform-provider-azuread#215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
Terraform v0.12.19
Issue present in both azureAD 0.6.0 and azureAD 0.7.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
provider "azuread" {
  version = "0.7.0"
}

resource "azuread_application" "application" {
  name                       = "example-site3"
  homepage                   = "https://examplesite3.com"
  identifier_uris            = ["https://examplesite3.com"] 
reply_urls                 =  ["https://test.examplesite3.com:8443/plugins/servlet/saml/auth"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
  group_membership_claims    = true
  type                       = "webapp/api"

}

resource "azuread_service_principal" "saml_based_service_principal" {
  application_id               = azuread_application.application.application_id
  app_role_assignment_required = false

  tags = ["WindowsAzureActiveDirectoryIntegratedApp", "WindowsAzureActiveDirectoryCustomSingleSignOnApplication", "WindowsAzureActiveDirectoryGalleryApplicationNonPrimaryV1"]
}

```
### Expected Behavior
AD application created with identifier_uris set 

### Actual Behavior

Front page shows identifier_uris set, however when you press enter it shows its not been set.

![image](https://user-images.githubusercontent.com/7372737/74448413-d41b0400-4e72-11ea-9722-f958a7f01e1b.png)

As you can see from the screen shot above its not really set which means the saml endpoint stays disabled when you move away from the page unless you manually add the value

### Steps to Reproduce

1. `terraform apply`

**Comment by manicminer** [comment]
Hi @MarkDordoy, thanks for reporting this. I believe this is an issue with Azure as I am encountering the same behavior whether I configure an App ID URI using the provider, or manually in the portal. When configuring the App ID URI using the provider, it's definitely getting set correctly on the Application object.

I don't believe these are supposed to be the same fields anyway? I suspect the SAML configuration showing you the App ID URI at all is actually a bug.

**Comment by manicminer** [comment]
Thanks again for reporting this @MarkDordoy. I'm going to close this as I believe the behavior we're seeing is correct. I can't find any documentation to the contrary, and as mentioned I think this _may_ be down to either a bug or inconsistency in the portal. Please feel free to comment further if you find otherwise and we can happily take another look.

**Comment by MarkDordoy** [comment]
@manicminer sorry for the late reply. I also believe even seeing this in the portal is a bug. 
 
Hopefully this will be configurable once the switch the the graph API happens as the beta servicePrincipal API has much more support for configuration. It's a bit off topic here, but i'd love to get the API used that can enable the SAML endpoint for the service principal. Ive tested the API and it works, however it is using the graph. 

Once i have that, and the support for saml2token optional claims support (which i see we are waiting for a bug in the SDK to be fixed), then i will have a fully automated pipeline to define and deploy my Saml Apps via code. 

Thanks for starting to get regular updates into the repo.

**Comment by manicminer** [comment]
@MarkDordoy No worries, thanks for posting back!

Feel free to raise issues for feature requests even if they depend on MS Graph, so they can be voted on. I haven't yet tested SAML configurations via MS Graph so any example/demo implementations you might have would also be super helpful.

**Comment by MarkDordoy** [comment]
Here is the doc re Automating SSO/SAML which would be great to offer as part of terraform: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-saml-sso-configure-api
@manicminer

**Comment by manicminer** [comment]
@MarkDordoy thanks, I've noted that on the SAML issue #173
