### ISSUE TITLE
Use directly graph.microsoft.com for non existing resources instead of azure sdk for go

### ISSUE THREAD

**Issue by phenixdotnet** [terraform-providers/terraform-provider-azuread#235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can we implement call to graph.microsoft.com directly in this provider instead of waiting an update of the azure sdk for go ? There is an [issue](https://github.com/Azure/azure-sdk-for-go/issues/7352) open to update to graph.microsoft.com but there is not ETA.

By doing this, we can add new resources and fix [others](https://github.com/terraform-providers/terraform-provider-azuread/issues/208) if needed and use the sdk when they are ready to use MS Graph API

If this is something acceptable, I can have a look at it.

### New or Affected Resource(s)
* azuread_application

And may be with a feature flag "beta"
* [azuread_trustframework_policy](https://docs.microsoft.com/en-us/graph/api/resources/trustframeworkpolicy?view=graph-rest-beta)
* [azuread_trustframework_keyset](https://docs.microsoft.com/en-us/graph/api/resources/trustframeworkkeyset?view=graph-rest-beta)
* [azuread_userflow](https://docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta)

### References

* #208 
* #175 
* [Azure SDK for Go Azure Active Directory API Deprecated](https://github.com/Azure/azure-sdk-for-go/issues/7352)

**Comment by LaurentLesle** [comment]
yes agreed. For example I cannot delete an azure ad group when I execute terraform from a service principal. This is something the microsoft graph support through more granular api permissions. The workaround was to make local exec calls. Now with the when-destroy not supported in latest terraform It is not possible to maintain a consistent state in Azure ad resources

**Comment by manicminer** [comment]
Hi @phenixdotnet, thanks for raising this as a potential way forward for us to begin using the Microsoft Graph API. Whilst there may be potential in this, it would not be our preferred approach and we are not yet in a position to decide on this. As this forms part of our larger strategy on migrating to MS Graph, and there is [another open issue](#193) tracking this, I'm going to close this issue in favor of that one to keep discussion in one place.
