### ISSUE TITLE
data.azuread_user mail_nickname does not use equals filter

### ISSUE THREAD

**Issue by patrickmarabeas** [terraform-providers/terraform-provider-azuread#237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

0.12.16

### Affected Resource(s)

* `azuread_user`

### Terraform Configuration Files

```hcl
data "azuread_user" "user" {
  mail_nickname = "xxx"
}
```

### Expected Behavior

Return the user.

### Actual Behavior

```
Error: Error finding Azure AD User with email alias "xxx": Found multiple AD Users matching "startswith(mailNickname,'xxx')"
```

Is there some reason why this is using `startswith` rather than `equals`?

Example cases where you look up `john.smit` and the following mail nicknames exist:
- john.smit
- john.smith
- john.smith2

or `smithj` where the following mail nicknames exist:
- smithj
- smithj2

**Comment by katbyte** [comment]
@patrickmarabeas, good catch, that should definitely not be a starts with, opened #251 to fix it 🙂

**Comment by Console32** [comment]
The reason why this was startsWith is described in #161

**Comment by mcpappas** [comment]
More specifically, the reason why this was changed to startsWith is described in #160. That is, better support for looking up guest members. Is there a way we can better support guest user lookup that doesn't result in unexpected behavior for others? Perhaps a dedicated "guest = true/false" flag that alters the lookup logic?
