### ISSUE TITLE
Removing group_membership_claims causes error

### ISSUE THREAD

**Issue by markti** [terraform-providers/terraform-provider-azuread#249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.12.18
+ provider.azuread v0.7.0
+ provider.azurerm v2.6.0
+ provider.random v2.2.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "aad_app" {
  name                        = var.name
  homepage                    = var.homepage
  identifier_uris             = var.identifier_uris
  reply_urls                  = var.reply_urls
  available_to_other_tenants  = var.available_to_other_tenants
  oauth2_allow_implicit_flow  = var.allow_implicit_flow
  group_membership_claims     = "SecurityGroup"
}
```

### Panic Output

Error: Error patching Azure AD Application with ID "673d651a-c418-4c43-8b31-e485d1ebb299": graphrbac.ApplicationsClient#Patch: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2020-05-13T01:30:21","message":{"lang":"en","value":"Invalid value specified for property 'groupMembershipClaims' of resource 'Application'."},"requestId":"8abc4778-c52f-496f-8803-08aa3ce3b72b","values":[{"item":"PropertyName","value":"groupMembershipClaims"},{"item":"PropertyErrorCode","value":"InvalidValue"}]}}]

### Expected Behavior

Enable group_membership_claims by setting the value to "SecurityGroup"
Then disable it by completely removing the tag. 
Should update the app to not have group membership claims.

### Actual Behavior

Causes an error.

### Steps to Reproduce

1. add group_membership_claims     = "SecurityGroup" to an azuread_application
2. `terraform apply`
3. completely remove group_membership_claims field from the resource.
4. `terraform apply`
5. watch it error

### Important Factoids

Azure Public Cloud

**Comment by manicminer** [comment]
Hi @markti, thanks for raising this issue. `groupMembershipClaims` is an optional property for Applications, but it defaults to `None`. In order to deconfigure, you'll need to set the explicit value of `None`.

The following two configurations are equivalent:
```hcl
resource "azuread_application" "test" {
  name = "myapp"
}
```
```hcl
resource "azuread_application" "test" {
  name = "myapp"
  group_membership_claims = "None"
}
```

Hope this helps.
