### ISSUE TITLE
Breaking change to oauth2_permissions

### ISSUE THREAD

**Issue by hbuckle** [terraform-providers/terraform-provider-azuread#265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

terraform -v
Terraform v0.12.26
+ provider.azuread v0.10.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "cluster_explorer" {
  name                       = "hbtesting-explorer"
  type                       = "webapp/api"
  homepage                   = "https://testy.com"
  identifier_uris            = ["https://testy.com"]
  reply_urls                 = ["https://testy.com"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = true
}

resource "azuread_application" "cluster_console" {
  name                       = "hbtesting-console"
  type                       = "native"
  reply_urls                 = ["urn:ietf:wg:oauth:2.0:oob"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = true

  required_resource_access {
    resource_app_id = azuread_application.cluster_explorer.application_id

    resource_access {
      id   = azuread_application.cluster_explorer.oauth2_permissions[0].id
      type = "Scope"
    }
  }
}

```

### Expected Behavior

In 0.9 this worked, because oauth2_permissions was a list

### Actual Behavior

In 0.10 oauth2_permissions has changed to a set, so you get 

```
Error: Invalid index

  on resource-ad.tf line 71, in resource "azuread_application" "cluster_console":
  71:       id   = azuread_application.cluster_explorer.oauth2_permissions[0].id

This value does not have any indices.
```

To get it to work you now have to do

```
id   = [for permission in azuread_application.cluster_explorer.oauth2_permissions : permission.id][0]
```

**Comment by manicminer** [comment]
Hi @hbuckle, thanks for raising this issue. This change was not intended to be a breaking one, I'm sorry about that. We've discussed internally and objectively this should probably remain as a set, unless there are un-workable consequences we haven't yet seen. We really appreciate you raising this and sharing your workaround.

I've opened a PR to note this in the changelog, as it should have been prior to release, and we'll take better care of documenting (or avoiding) these in future.

**Comment by magne** [comment]
There are at least two issues with keeping `oauth2_permissions` as a set:
- The azuread_application data source still maintains `oauth2_permissions` as a list, creating a discrepancy between two essentially equal objects.
- It makes it even harder to select the correct id from the set of permissions (for use in `required_resource_access`) based on `value`

Earlier, I could use:
```
...
  required_resource_access {
    resource_app_id = azuread_application.api.application_id
    resource_access {
      id   = azuread_application.api.oauth2_permissions[index(azuread_application.api.oauth2_permissions.*.value, "API.All")].id
      type = "Scope"
    }
...
```
This is no longer possible. The workaround above is possible to use, but it makes an already awkward construction even worse:
```
[for permission in azuread_application.api.oauth2_permissions : permission][index([for permission in azuread_application.api.oauth2_permissions : permission].api.oauth2_permissions.*.value, "API.All")].id
```
This also assumes that the `for` expression always iterates the set in the same order. (An alternative is to extract the list to a local variable).

**Comment by hbuckle** [comment]
I don't have a problem with it being a set, just wanted to flag that it was a breaking change, although the resource and the data source should probably use the same construct.

@magne I think you can do

```hcl
      id   = [
        for permission in azuread_application.api.oauth2_permissions : id if permission.value == "API.All"
      ][0]
```
Which is simpler

**Comment by tombuildsstuff** [comment]
@hbuckle @magne there's a limitation in Terraform where Data Sources can't use Sets (since they all end up with the same hash code, so only a single item is present) - which is why we use Lists instead of Sets in Data Sources - that said this should be mapable between the two in user configuration using Terraform's interpolation functions?

**Comment by magne** [comment]
@hbuckle Nice, didn't see that one. One small change, and it works :-)
```hcl
id = [
  for permission in azuread_application.api.oauth2_permissions : permission.id if permission.value == "API.All"
][0]
```

@tombuildsstuff I see that also resource app_role is a set, and data source app_role***s*** is a list (note that it is called app_role and app_roles!). Since the construct provided by @hbuckle can be used with both lists and sets, I'm inclined to say it's OK, although I find it less than desirable to have different APIs for essentially the same object.

**Comment by mbenabda** [comment]
if that helps, i find this a tad easier to read :

```hcl
data "azuread_service_principal" "microsoft_graph_api" {
  display_name = "Microsoft Graph"
}

locals {
  # turn the permissions set back into a list
  microsoft_graph_api_oauth2_permissions = [for permission in data.azuread_service_principal.microsoft_graph_api.oauth2_permissions : permission]
  microsoft_graph_api_oauth2_scope_ids   = zipmap(local.microsoft_graph_api_oauth2_permissions.*.value, local.microsoft_graph_api_oauth2_permissions.*.id)
}
```

Then use it like this:
```hcl
resource "azuread_application" "my_app" {
  ...
  required_resource_access {
    resource_app_id = data.azuread_service_principal.microsoft_graph_api.application_id

    resource_access {
      id   = local.microsoft_graph_api_oauth2_scope_ids["Group.Read.All"]
      type = "Scope"
    }
  }
...
}
...
```

**Comment by manicminer** [comment]
Thanks all for the discussion and workaround. Since we're going to leave this change in place, I'll close this issue, but please feel free to comment further if there are other corner cases we haven't yet noticed.
