### ISSUE TITLE
azuread_application: homepage can't be blank

### ISSUE THREAD

**Issue by magne** [terraform-providers/terraform-provider-azuread#268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.12.26
+ provider.azuread v0.10.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "api" {
  name     = "My App"
  homepage = ""

  oauth2_permissions {
    type                       = "User"
    value                      = "API.All"
    admin_consent_description  = "Access to the API."
    admin_consent_display_name = "Access to the API."
  }
}
```

### Expected Behavior

I expected the application to be created with a blank homepage (I'm creating an internal API app registration, and it doesn't have an obvious homepage).

### Actual Behavior

Terraform reports an error:
```
Error: expected "homepage" url to not be empty
```

Also, if I try to leave out `homepage`, terraform fails with:
```
Error: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_BadRequest","date":"2020-06-09T09:35:04","message":{"lang":"en","value":"Url is malformed paramName: WwwHomepage, paramValue: https://My App, objectType: Microsoft.Online.DirectoryServices.Application"},"requestId":"07137f59-663e-4292-bc3f-28ddddc14628","values":[{"item":"PropertyName","value":"homepage"},{"item":"PropertyErrorCode","value":"NotAWellFormedUrl"}]}}]
```
This happens because of the default value of `https://{name}` for `homepage`, since my app registration has a name that is unsuitable for an url.

The obvious workaround is of course to set `homepage` to a valid url, but this should not be necessary.

### Steps to Reproduce

1. `terraform init`
1. `terraform apply`

**Comment by manicminer** [comment]
@magne thanks for requesting this. I believe the current behaviour of setting a default homepage (signInUrl) might stem from supporting legacy application registrations, however I'll look further into that. We'll look at updating this to allow unsetting a homepage URL.

**Comment by manicminer** [comment]
Just an update, this is a sticky one as the SDK (and possibly the AAD Graph API) does not support null values for the homepage (aka signInUrl), and as per the above report, it cannot be cleared by setting to an empty string.

I've opened a PR #278 to stop deriving a default value for `homepage`, which will hopefully mitigate the issue in that applications can be created without a homepage. This issue should remain open until we can resolve being able to unset the property.

I've opened an upstream issue https://github.com/Azure/azure-sdk-for-go/issues/10463

**Comment by manicminer** [comment]
Since changing the behavior of the `homepage` attribute could potentially break existing configurations, support for empty homepage values will be available in the next major version of the provider. Even so, there are caveats to what we can accomplish due to missing SDK support for clearing this field once it has been set. Kindly see the linked PR #278 for details.
