### ISSUE TITLE
tags argument for AzureAD inconsistent with AzureRM

### ISSUE THREAD

**Issue by dkirrane** [terraform-providers/terraform-provider-azuread#270]
azuread `azuread_service_principal` tags uses `list(string)`
https://www.terraform.io/docs/providers/azuread/r/service_principal.html#tags

whereas all the azurerm tags use `map(string)` e.g:
https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html#tags

Could this be consistent? I'd like to use `map(string)` everywhere in my Plan.
Or is there an easy way to convert tags `map(string)` to `list(string)` and still be able to filter by tag from Portal?

**Comment by manicminer** [comment]
Hi @dkirrane, thanks for requesting this.

Tags for service principals are different to tags you might encounter elsewhere in Azure. They are not represented as key-value pairs and the values have explicit meanings. To my knowledge, they are mainly used to identity different types of Enterprise Applications (which are represented by service principals in AAD). For example, SAML apps will have a tag `WindowsAzureActiveDirectoryCustomSingleSignOnApplication` ([source](https://docs.microsoft.com/en-us/answers/questions/24259/identify-saml-enabled-apps-in-azure-ad.html)).

I have not seen this documented authoritatively anywhere, however you can reverse engineer tag values by using the Enterprise Applications blade in the Azure Portal to create some service principals with different configurations, and then query them. We don't specifically support SAML apps at this time however.

**Comment by manicminer** [comment]
I'm going to close this issue, but please feel free to comment further if I can help clarify.
