### ISSUE TITLE
azuread_user does not find Guest users by user_principal_name

### ISSUE THREAD

**Issue by trajano** [terraform-providers/terraform-provider-azuread#275]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

0.10.0

### Affected Resource(s)

data "azuread_user" 

### Terraform Configuration Files

```hcl
data "azuread_user" "YYYY" {
  user_principal_name = "YYYY@ZZZZ.com"
}
```

### Expected Behavior

It should find the user

### Actual Behavior

```
Error: Error making Read request on AzureAD User with ID "XXXXXXX": graphrbac.UsersClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_ResourceNotFound","date":"2020-06-15T10:42:18","message":{"lang":"en","value":"Resource 'XXXXXXXXXX' does not exist or one of its queried reference-property objects are not present."},"requestId":"c20c2561-194c-4ef9-b939-7a2322c38bf0"}}]
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

`object_id` still works.

The following also works so if we had a `mail` option for the `data "azuread_user"` this would solve the issue.  It should throw an error if it detects that the query will return more than one result.
```
az ad user list --filter "mail eq 'email@guest.com'"
```

### References

* #193 may fix this, but there's no specific bug report for this specific scenario

**Comment by manicminer** [comment]
Hi @trajano, thanks for raising this. Are you querying for a guest account (i.e. domiciled in a different tenant) or a regular user? Is the user returned when you query using the Azure CLI?
```shell
az ad user show --id user@principal.name
```

**Comment by trajano** [comment]
@manicminer yup I know about `user_home.com#EXT#@guest.net` but Portal already shows the e-mail and I am hoping to use the same.  Or perhaps add a different parameter perhaps "guest" to indicate that the user is a guest which also means the lookup may need to be different.

![image](https://user-images.githubusercontent.com/110627/84699133-ff942500-af1e-11ea-9b64-935c91689c38.png)

**Comment by manicminer** [comment]
Whilst I think that might be a useful shortcut, ultimately this is AAD business logic that I don't believe we should incorporate. You can construct a guest UPN fairly simply with the `replace()` string function. For example:

```hcl
provider "azuread" {}

locals {
  user_name = "user@home.com"
  tenant_domain = "othertenant.onmicrosoft.com"
  user_principal_name = "${replace(local.user_name, "@", "_")}#EXT#@${local.tenant_domain}"
}

data "azuread_user" "test" {
  user_principal_name = local.user_principal_name
}

output "user_id" {
  value = data.azuread_user.test.id
}
```

Hope this helps :)

**Comment by trajano** [comment]
What about using `mail` as a lookup?  You already have `mailNickName`

**Comment by manicminer** [comment]
@trajano Great suggestion, I think we can do that! Would you kindly open another issue to request that?
