### ISSUE TITLE
azuread_group members array of user objects

### ISSUE THREAD

**Issue by patrickmarabeas** [terraform-providers/terraform-provider-azuread#288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azuread_group` should return an array of `user` objects (same as `azuread_user` outputs) rather than just the `object_id.

### New or Affected Resource(s)

* azuread_group (data)
* azuread_group (resource)

---

I'm happy to kick off the PR if this is an acceptable feature.

**Comment by manicminer** [comment]
Hi @patrickmarabeas, thanks for requesting. I'm wondering if this is really necessary given that you'll soon be able to do something like this?

```hcl
data "azuread_group" "test" {
  name = "testgroup"
}

data "azuread_users" "test_members" {
  object_ids = data.azuread_group.test.members
}
```

Would this work in your configuration?

**Comment by patrickmarabeas** [comment]
Sorry, I was assuming the API response. I was looking to avoid hitting it twice, but that would be required anyway.
