### ISSUE TITLE
Support creation of Azure AD Service Principal with certificate

### ISSUE THREAD

**Issue by t0klian** [terraform-providers/terraform-provider-azuread#29]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add ability to create Azure AD Service Principal with certificate using azuread_service_principal_certificate or updated azuread_service_principal resources as it is described in below documentation reference

### New or Affected Resource(s)

* azuread_service_principal_certificate
* azuread_service_principal

### References

https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest

**Comment by phrueegsegger** [comment]
need that too.

**Comment by manicminer** [comment]
Hi @t0klian, thanks for requesting this!

Although we currently support AAD application and service principal secrets/passwords, we cannot currently manage certificates for these as there is missing SDK support. I've marked this issue as upstream-dependent and we'll revisit this as soon as we are able.

The corresponding upstream issue is [here](https://github.com/Azure/azure-sdk-for-go/issues/7352) if you would like to vote for it.

**Comment by manicminer** [comment]
Sorry, kindly disregard my earlier comment! Located in the SDK with its API nomenclature. PR incoming.
