### ISSUE TITLE
Terraform fails to retreive Azure AD resources - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by roeizavida** [terraform-providers/terraform-provider-azuread#296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
Terraform v0.12.24
+ provider.azuread v0.11.0
+ provider.azurerm v2.18.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.3.0
```

### Affected Resource(s)

* `azuread_group`
* `azuread_application`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azuread_application" "application" {
  name                       = var.aadApplicationName
  homepage                   = "https://${var.aadApplicationName}"
  identifier_uris            = ["https://${var.aadApplicationName}"]
  reply_urls                 = ["https://${var.aadApplicationName}"]
  available_to_other_tenants = false
}

data "azuread_group" "keyvault_group" {
  name = var.keyVaultGroupName
}
```

### Debug Output

```
Error: retrieving Azure AD Application with ID "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx": graphrbac.ApplicationsClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get "https://graph.windows.net/"xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx":/applications/"xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx":?api-version=1.6": x509: certificate signed by unknown authority

Error: retrieving Azure AD Application with ID ""xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx":": graphrbac.ApplicationsClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get "https://graph.windows.net/"xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx":/applications/"xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx":?api-version=1.6": x509: certificate signed by unknown authority

Error: Error finding Azure AD Group with display name "Developers": listing Azure AD Groups for filter "displayName eq 'Developers'": graphrbac.GroupsClient#List: Failure sending request: StatusCode=0 -- Original Error: Get "https://graph.windows.net/"xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx":/groups?%24filter=displayName+eq+%27Developers%27&api-version=1.6": x509: certificate signed by unknown authority

 on key_vault.tf line 13, in data "azuread_group" "keyvault_group":
 13: data "azuread_group" "keyvault_group" {
```
### Expected Behavior

Terraform should retrieve the Azure AD resources from Azure.

### Actual Behavior

Terraform fails to retrieve the Azure AD resources from Azure.

### Steps to Reproduce

1. `az login`
2. `terraform apply`

### Important Factoids

Running behind corporate proxy. It worked until a few days ago.
Using Azure CLI or graph API directly is working with the same account that Terraform is using (it is not a service principal).

### References

* #0000

**Comment by manicminer** [comment]
Hi @roeizavida, it looks like you might have an intercepting proxy issuing an untrusted certificate. This is a configuration issue that you will need to resolve on your system.
