### ISSUE TITLE
Issues with features block in azuread provider

### ISSUE THREAD

**Issue by sangeethaguhan** [terraform-providers/terraform-provider-azuread#299]
hi @jbobbylopez & @tombuildsstuff

I'm using **Terraform v0.12.29 and azuread provider 0.11.0.**
I followed the documentation [here](https://www.terraform.io/docs/providers/azuread/guides/service_principal_client_secret.html): 
```
provider "azuread" {
  # Whilst version is optional, we /strongly recommend/ using it to pin the version of the Provider being used
  version = "=0.10.0"
}
```

There is no mention of features block here, but terraform enterprise expects a features block when I execute. So I added features block and gave a run but in rain. It now says, "unsupported block type features{}"

**Quite confused with the way features block works with azurerm and azuread provider.** I'm using azuread provider because, in my code I'm trying to create service principals. Please assist with the right provider block for azurerm/azuread and help me authenticate to azure via Terraform Enterprise, thank you!

Thanks!

_Originally posted by @tombuildsstuff in https://github.com/terraform-providers/terraform-provider-azuread/issues/219#issuecomment-594218078_

**Comment by tombuildsstuff** [comment]
hi @sangeethaguhan 

Thanks for opening this issue.

This forum is intended to be used for Bugs and Feature Requests - as such whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment. However as a Terraform Enterprise user, I'd suggest opening an issue with [HashiCorp Support](https://support.hashicorp.com) who should be able to assist further here.

Thanks!
