### ISSUE TITLE
Provide support for approle outside of resource_application as an independent resource

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-azuread#306]
### Description

Currently it is only possible to create approles through an application (resource_application.go)

In our AD setup, an enterprise application is created for us by another team, and we can only create approles within it. We have no permission to be able to create or modify enterprise applications, but would like to be able to create and assign approles to users. 

As with many terraform resources, it would be useful if both approaches were possible.

### New or Affected Resource(s)

resource_application.go

**Comment by manicminer** [comment]
Hi @gtmtech, thanks for requesting this! We have been considering additional standalone resources for applications, with the goal of making it possible to have more flexible configurations.

Until this is implemented, would you be able to work around this by importing the already existing application into your state? For example:

```shell
terraform import azuread_application.my_app 10000000-2000-3000-4000-500000000000
```

This will allow you to manage aspects of the application using Terraform, without needing to create it with Terraform in the first place.
