### ISSUE TITLE
azuread_application using prevent_duplicate_names does not ignore provisioned app

### ISSUE THREAD

**Issue by nerddtvg** [terraform-providers/terraform-provider-azuread#310]
https://github.com/terraform-providers/terraform-provider-azuread/blob/d2dfb01976da48d3ff14e92b6858c182da6c2536/azuread/helpers/graph/application.go#L288-L290

When utilizing prevent_duplicate_names, the provisioning process will error out after the app has been created and during the application of other values. The check should ignore the provisioned application that it is updating.

**Comment by manicminer** [comment]
@nerddtvg Thanks for reporting this bug, we'll look at remediating as soon as we are able.

**Comment by Peter-Sternberger** [comment]
Hit the same problem, would appreciate the prevent_duplicate_names check

**Comment by tareks** [comment]
Impacted by this as well. Seems to only happen with `azuread_application` but not `azuread_group`. If a new resource is created with `prevent_duplicate_names = true` it will fail with the following error:

```
Error: existing Application with name "<redacted>" (AppID: "redacted") was found and `prevent_duplicate_names` was specified

```

**Comment by nerddtvg** [comment]
Thank you so much!

**Comment by scott-doyland-burrows** [comment]
Hi,
The problem still seems to exist with provider 1.1.0.
I try to create an app registration which does NOT yet exist using:
```prevent_duplicate_names = true```

and still get the error.  The application ID in the error IS the application ID of the app registration that terraform has partially managed to create before it has the error.
```
Error: existing Application with name "burrows-appreg-scott-cadabraui" (AppID: "a79564a0-72cb-4b2d-855e-83079eb05929") was found and `prevent_duplicate_names` was specified

  on cadabraui.tf line 1, in resource "azuread_application" "cadabraui":
   1: resource "azuread_application" "cadabraui" {


terraform version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.1.0
+ provider registry.terraform.io/hashicorp/azurerm v2.37.0
```
