### ISSUE TITLE
Add Data Source to Retrieve Azure AD Access Token for a Service Principal

### ISSUE THREAD

**Issue by PSanetra** [terraform-providers/terraform-provider-azuread#321]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to have some data source which returns a valid access token for a service principal given some client id and client secret. We need this token to execute some postgresql scripts in our CICD pipeline with the credentials of an AAD user. Similar like it is documented here: https://docs.microsoft.com/en-us/azure/postgresql/howto-configure-sign-in-aad-authentication#step-3-use-token-as-password-for-logging-in-with-postgresql

### New or Affected Resource(s)

* azuread_token (?)

### Potential Terraform Configuration

```hcl
data "azuread_token" "postgres_token" {
  client_id = "[service_principal_id]"
  client_secret = "[service_principal_secret]"
  resource = "https://ossrdbms-aad.database.windows.net"
}

resource "null_resource" "my_resource" {
    command = "./my_script.sh"
    environment = {
      AZURE_TOKEN = data.azuread_token.postgres_token.token
    }
}
```

**Comment by manicminer** [comment]
Hi @PSanetra, thanks for requesting this. I don't think this is a good candidate for a data source, because the access token rotates quickly (between 5-60 minutes) it would cause unnecessary state diffs.

Have you considered adding the token acquisition to your script? Either using the example from the docs with Azure CLI, or just making a POST request and parsing the response? v1 tokens are quite simple to work with.

e.g.
```hcl
resource "null_resource" "postgres_things" {
  provisioner "local-exec" {
    command = "./script.sh"
  }

  environment = {
    TENANT_ID     = "[tenant_id]"
    CLIENT_ID     = "[client_id]"
    CLIENT_SECRET = "[client_secret]"
  }
}
```

with either:

```sh
#!/bin/sh

az login --service-principal --tenant "${TENANT_ID}" --username "${CLIENT_ID}" --password "${CLIENT_SECRET}"
TOKEN="$(az account get-access-token --resource-type oss-rdbms | jq -r .accessToken)"

# do some things
```

or:

```sh
#!/bin/sh

TOKEN="$(curl -i -X POST \
  -d "client_id=${CLIENT_ID}" \
  -d "client_secret=${CLIENT_ID}" \
  -d "grant_type=client_credentials" \
  -d "resource=https://ossrdbms-aad.database.windows.net" \
  "https://login.microsoftonline.com/${TENANT_ID}/oauth2/token" \
  | jq -r .access_token)"

echo $TOKEN
```

**Comment by PSanetra** [comment]
@manicminer yes, we are currently using the second approach. We thought it would be nice to get the token via a terraform data source. But you are right, there might be use cases where the data sources are not always refreshed.

**Comment by manicminer** [comment]
@PSanetra No worries, glad you have a solution that works for you! I'm going to close this one, but please feel free to open any other feature requests you think would be useful :)
