### ISSUE TITLE
Development of this Terraform Provider

### ISSUE THREAD

**Issue by MarkDordoy** [terraform-providers/terraform-provider-azuread#322]
@manicminer Id be really keen to start adding features to this provider that help support building and managing enterprise apps that are primarily used for SAML integrations. 

The features id like to help develop would be:
* Azure AD Policy resource 
* More features around AD Service Principals 
-- Enable SAML Endpoint
-- Generate Signing certificates
-- Set Notification Emails
-- Support RelyState 
* Azure AD Application Registration 
-- Support additional changes to the app manifest 

My main concern is that most, if not all the above requests interact with the Microsoft Graph, however from previous conversations with you my understanding is the GO SDK does not yet support this. However there are plans to move this provider to use this new graph since the Azure AD graph is now deprecated. 

Are you able to share how you plan to make this Provider interact with the graph API. As i'd hate to try some of this, go down a particular path only to have it rejected as it does not follow the plan for this repo. 

I look forward to your response. 

Thanks

**Comment by manicminer** [comment]
Hey @MarkDordoy, that's fantastic and greatly appreciated. SAML apps/integrations are a particular area where expertise is welcomed. App registrations also have a ton of featured waiting to be added.

You're right that most of everything relies on MS Graph; as I've hinted in a few threads, we're actively working on that and after checking out various potential options we decided to roll our own SDK. Most likely we'll move away from the Azure Go SDK entirely. This is still in progress - whilst being straightforward in principle we're casting a wide net and looking at autogeneration amongst other things. There's now a pinned issue on this repo #323 to publish our progress. It purposely doesn't get down to brass tacks but should give a good idea of where we're at and what our plans are.

If you aren't already a member, do consider joining our community Slack workspace (details in the project readme) - it's a great space to collaborate on details. Likewise, for the features you're looking at, consider creating issues for visibility and so they can be upvoted.

**Comment by MarkDordoy** [comment]
Hey @manicminer thanks for the quick reply, I'll make sure to add myself to the slack workspace.  

So while we wait for this new SDK to be ready to consume and use, would you be against raw REST api calls into a struct and go from there? Or should i wait for the first release of the SDK? I know you likely wont want to say, but do you know when the SDK in beta/Alpha will be ready to test out?

**Comment by manicminer** [comment]
@MarkDordoy thanks for reaching out on Slack. Given that we're actively working on it, I don't think we'll merge interim implementations as it will add complexity and potential conflicts as code is refactored.

I'm going to go ahead and close this issue, as we're tracking progress in the pinned issue and further discussion is probably better suited on Slack. Thanks!
