### ISSUE TITLE
Docs are gone for terraform-provider-azuread

### ISSUE THREAD

**Issue by phatcher** [terraform-providers/terraform-provider-azuread#332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_XXXXX`

### Expected Behavior

Should see the docs

### Actual Behavior

Get a 404 on https://registry.terraform.io/providers/hashicorp/azuread/latest/docs and other pages

**Comment by manicminer** [comment]
Hi @phatcher, thanks for reporting. I believe this is a known issue on the Registry site that has been quickly remediated.
