### ISSUE TITLE
Adding members from a resource "azuread_user" when using for_each

### ISSUE THREAD

**Issue by Grant-Rc** [terraform-providers/terraform-provider-azuread#346]
### Terraform (and AzureAD Provider) Version

terragrunt version v0.19.24
Terraform v0.12.9
provider "azuread" {
  version = "=0.7.0"
}

### Affected Resource(s)

* `azuread_azuread_group'

### Terraform Configuration Files

`provider "azuread" {
  version = "=0.7.0"
}

resource "azuread_user" "admin_user" {
  for_each = var.users
  user_principal_name = lower(each.value)
  display_name        = each.key
  password            = "SecretP@sswd99!"
  force_password_change = true
}

resource "azuread_group" "admin_group" {
  for_each = azuread_user.admin_user
  name    = "azure admins"
  members = "${lookup(each.value, "id", "*")}"
}`

### Debug Output

Error: Incorrect attribute value type

  on main.tf line 23, in resource "azuread_group" "admin_group":
  23:   members = "${lookup(each.value, "id", "*")}"

Inappropriate value for attribute "members": set of string required.

### Expected Behavior

Excepting the user accounts from the creation of resource "azuread_user" are added to the Group creation from resource "azuread_group"

### Actual Behavior

Fails to pass the correct value though

### Steps to Reproduce

Use the config above passing var.users fo your choosing

1. `terraform plan` or `terragrunt plan'

### Important Factoids

I found a way to do it which works as expected by creating the group and then adding the users seperatly.

`provider "azuread" {
  version = "=0.7.0"
}

resource "azuread_user" "admin_user" {
  for_each = var.users
  user_principal_name = lower(each.value)
  display_name        = each.key
  password            = "SecretP@sswd99!"
  force_password_change = true
}

resource "azuread_group" "admin_group" {
  name    = "azure admins"
}

resource "azuread_group_member" "example" {
  for_each = azuread_user.admin_user
  group_object_id   = azuread_group.admin_group.id
  member_object_id  = "${lookup(each.value, "id", "*")}"
}`

**Comment by manicminer** [comment]
Hi @Grant-Rc, thanks for opening this issue.

This is really a usage question, and as we use GitHub issues for tracking feature requests and bugs in the Azure provider, I recommend you check out our [Community Resources](https://www.terraform.io/community.html) and our [HashiCorp Learn](https://learn.hashicorp.com/terraform) portal.

However although there are a number of syntax issues with the snipped you posted, this should be easy to rectify. Assuming you want to create some users, then add them to a group, you'll want something like this:

```hcl
resource "azuread_user" "admin_user" {
  for_each              = var.users
  user_principal_name   = lower(each.value)
  display_name          = each.key
  password              = "SecretP@sswd99!"
  force_password_change = true
}

resource "azuread_group" "admin_group" {
  name    = "azure admins"
  members = values(azuread_user.admin_user).*.object_id
}
```

or alternatively, this

```hcl
resource "azuread_user" "admin_user" {
  for_each              = var.users
  user_principal_name   = lower(each.value)
  display_name          = each.key
  password              = "SecretP@sswd99!"
  force_password_change = true
}

resource "azuread_group" "admin_group" {
  name    = "azure admins"
}

resource "azuread_group_member" "admin_group" {
  for_each         = azuread_user.admin_user
  group_object_id  = azuread_group.admin_group.object_id
  member_object_id = each.value.object_id
}
```

I hope this helps! I'm going to close this issue for now, as I don't believe there's anything for us to do here, but you should be able to get further answers via our community channels.
