### ISSUE TITLE
Failure to retreive obecjts (users and groups) with MSI authentication

### ISSUE THREAD

**Issue by gitmaximd** [terraform-providers/terraform-provider-azuread#347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
Terraform v0.12.29
+ provider.azuread v1.0.0

### Affected Resource(s)

* `azuread_group`
* `azuread_user`

### Terraform Configuration Files

```hcl
provider "azuread" {
  use_msi = true
}

data "azuread_group" "aks_rbac" {
  name = "AKSAdmins"
}

data "azuread_user" "example" {
  user_principal_name = "some_user@domain.com"
}

output "oid" {
  value = data.azuread_user.example.object_id
}

output "id" {
  value = data.azuread_group.aks_rbac.id
}

```

### Debug Output

https://gist.githubusercontent.com/gitmaximd/dff9087b41dd82b0c6c60c18f2880481/raw/25adc49c57825023efe1e7007c8a47292d5c4260/gistfile1.txt
### Expected Behavior

Successfully retrieve user or group object information

### Actual Behavior

While using MSI for authentication the data resource fails to retrieve the information. Same code works with SP authentication.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I noticed that the request URL is incorrectly constructed and is missing Tenant domain name. For example:
https://graph.windows.net//groups?%24filter=displayName+eq+%27AKSAdmins%27&api-version=1.6
It should be like this one: https://graph.windows.net/domain.com/groups?%24filter=displayName+eq+%27AKSAdmins%27&api-version=1.6
### References

* #0000

**Comment by manicminer** [comment]
Hi @gitmaximd, thanks for raising this issue! When using MSI authentication, you do also need to specify the tenant ID, either using the `tenant_id` argument in the provider block, or via the `ARM_TENANT_ID` environment variable. It's not possible for us to auto-determine the tenant from the MSI endpoint response.

Our documentation could be clearer about this, so I'm going to mark this issue as a documentation bug so that we can address this and make it clearer how you should configure the provider.

**Comment by manicminer** [comment]
We have added clarification to our documentation for authentication using a managed identity, that a tenant ID is always required. I believe this will resolve this issue, and so I'm going to close it for now. Please comment further if you continue to see this error after adding a tenant ID to your configuration and we'll be happy to reopen. Thanks!
