### ISSUE TITLE
Documentation for data.azuread_users is incorrect

### ISSUE THREAD

**Issue by BradAF** [terraform-providers/terraform-provider-azuread#349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `data.azuread_user` (v1.0.0)

### References

[https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/users](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/users)

### Issue

The title page is incorrect; reads **azuread_user** instead of **azuread_users**

The output from a user block does not contain the **id** attribute. It is instead named **object_id**

![image](https://user-images.githubusercontent.com/11336928/97709313-80982700-1a90-11eb-8f53-d5b41fad5a85.png)

**Comment by manicminer** [comment]
@BradAF Thanks for reporting! We'll fix up those documentation inconsistencies.
