### ISSUE TITLE
Owners on azuread_application resource can't be specified as an empty list

### ISSUE THREAD

**Issue by ChrisF987** [terraform-providers/terraform-provider-azuread#352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.0.0
```

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
provider "azuread" {
  version = "1.0.0"
}

resource "azuread_application" "this" {
  name = "MyAzureADApplication"
  owners = []
}
```

### Expected Behavior

Terraform plan and then apply creates the azuread_application resource without any Owners. This is what occurs when the Owners attribute is not supplied. 

### Actual Behavior

terraform plan errors with the following:
```
Error: owners: attribute supports 1 item as a minimum, config has 0 declared

  on main.tf line 5, in resource "azuread_application" "this":
   5: resource "azuread_application" "this" {
```
### Steps to Reproduce

1. `terraform plan`

### References

#353 is another issue I've raised with this `owners` attribute

**Comment by manicminer** [comment]
@ChrisF987 Thanks for reporting this bug. A fix for this is forthcoming in #355
