### ISSUE TITLE
Azure app registration fails when using prevent_duplicate_names

### ISSUE THREAD

**Issue by scott-doyland-burrows** [terraform-providers/terraform-provider-azuread#364]
Hi,
The problem still seems to exist with provider 1.1.0.
I try to create an app registration which does NOT yet exist using:
```prevent_duplicate_names = true```

and still get the error.  The application ID in the error IS the application ID of the app registration that terraform has partially managed to create before it has the error.
```
Error: existing Application with name "burrows-appreg-scott-cadabraui" (AppID: "a79564a0-72cb-4b2d-855e-83079eb05929") was found and `prevent_duplicate_names` was specified

  on cadabraui.tf line 1, in resource "azuread_application" "cadabraui":
   1: resource "azuread_application" "cadabraui" {


terraform version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.1.0
+ provider registry.terraform.io/hashicorp/azurerm v2.37.0
```

_Originally posted by @scott-doyland-burrows in https://github.com/terraform-providers/terraform-provider-azuread/issues/310#issuecomment-733863600_

**Comment by manicminer** [comment]
Hi @scott-doyland-burrows, thanks for reporting this. This was erroneously marked a resolved and there is a fix incoming.
