### ISSUE TITLE
The default owner of azuread_service_principal is not the owner who runs terraform apply in v1.1.0

### ISSUE THREAD

**Issue by moonape1226** [terraform-providers/terraform-provider-azuread#365]
Hi, I encounter some default owner problem in `azuread_service_principal` today.

Terraform (and AzureAD Provider) Version
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.1.0
+ provider registry.terraform.io/hashicorp/azurerm v2.36.0
```

Affected Resource(s)
```
azuread_application
azuread_service_principal
```

Terraform Configuration Files
```
resource "azuread_application" "test-application" {
  name = "test-application"
}

resource "azuread_service_principal" "test-sp" {
  application_id = azuread_application.test-application.application_id
}
```

### Debug Output
```
Error: patching Application with ID "xxx": graphrbac.ApplicationsClient#Patch: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-11-26T03:56:19","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"xxx"}}]
```

### Expected Behavior

In v1.0.0, the application registry created by terraform is owned by the user that ran `terraform apply` by default.
 
### Actual Behavior

However, in v1.1.0, the application registry created by terraform is no longer owned by the user that ran `terraform apply`. So I am not able to access the application registry I created in other resources.

### Steps to Reproduce

1. `terraform apply`

**Comment by manicminer** [comment]
Hi @moonape1226, thanks for reporting. We've done a lot of testing with application owners (along with some other complex properties) and agree that the default owner assigned by Azure AD should be retained. We'll be issuing a fix for this shortly.

**Comment by moonape1226** [comment]
Thanks for the prompt reply and update!
