### ISSUE TITLE
Support create-for-rbac

### ISSUE THREAD

**Issue by piizei** [terraform-providers/terraform-provider-azuread#40]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please support creating SPs equally to cmd line command az ad sp create-for-rbac --years 2

**Comment by joakimhellum-in** [comment]
Hi, running `az ad sp create-for-rbac --years 2` is the same as applying the following Terraform configuration:

```hcl
data "azurerm_subscription" "main" {}

resource "random_id" "main" {
  byte_length = 8
  prefix      = "terraform-"
}

resource "azuread_application" "main" {
  name                       = "${random_id.main.hex}"
  available_to_other_tenants = false
}

resource "azuread_service_principal" "main" {
  application_id = "${azuread_application.main.application_id}"
}

resource "random_string" "password" {
  length  = 32
  special = true
}

resource "azuread_service_principal_password" "main" {
  service_principal_id = "${azuread_service_principal.main.id}"
  value                = "${random_string.password.result}"
  end_date_relative    = "17520h"
}

resource "azurerm_role_assignment" "main" {
  scope                = "${data.azurerm_subscription.main.id}"
  role_definition_name = "Contributor"
  principal_id         = "${azuread_service_principal.main.id}"
}

output "display_name" {
  value = "${azuread_service_principal.main.display_name}"
}

output "client_id" {
  value = "${azuread_application.main.id}"
}

output "client_secret" {
  value     = "${azuread_service_principal_password.main.value}"
  sensitive = true
}

output "object_id" {
  value = "${azuread_service_principal.main.id}"
}
```

Creating a Terraform module out of this would allow you to design the right level of abstraction, so that it looks exactly like the `az ad sp create-for-rbac` command. Beware your credentials will be persisted into Terraform state.

**Comment by antoinne85** [comment]
@joakimhellum-in Which aspect of that configuration is responsible for the `create-for-rbac` aspect of `az ad sp create-for-rbac`? Phrased differently, if I just wanted to mimic `az ad sp create`, what would change? (Aside from the expiration, of course.)

I'm trying to use a service principal created w/ Terraform in an AKS cluster w/ a static IP in another resource group and getting hit with permissions errors. The support rep from Azure was pretty insistent it was because I was creating my service principal w/ Terraform instead of using the Azure CLI and the `create-for-rbac` argument. I'm not convinced that's the problem yet, but now I've got to jump through a whole bunch of hoops just to confirm that's _not_ the problem.

**Comment by joakimhellum-in** [comment]
@antoinne85 

> Which aspect of that configuration is responsible for the create-for-rbac aspect of az ad sp create-for-rbac? Phrased differently, if I just wanted to mimic az ad sp create, what would change?

In short `az ad sp create` only creates a service principal, while `create-for-rbac` creates a service principal and configures it's access to Azure resources.

Running `az ad sp create` does the following:
- Creates a Service Principal associated with an Azure AD Application (`azuread_service_principal`)

Running `az ad sp create-for-rbac` does alot more:
- Creates Azure AD Application (`azuread_application`)
- Creates a Service Principal associated with the Azure AD Application (`azuread_service_principal`)
- Creates credential for the Azure AD Application associated with the Service Principal (`azuread_service_principal_password`)
- Creates role assignment for the Service Principal (`azurerm_role_assignment`)
  - By default this is `Contributor` role in current subscription

> I'm trying to use a service principal created w/ Terraform in an AKS cluster w/ a static IP in another resource group and getting hit with permissions errors.

For creating a service principal and managed Kubernetes cluster with Terraform, see example configuration below.

<details>
 <summary>Show example Terraform configuration</summary>

```hcl
locals {
  name_prefix = "example"
}

# Create resource group
resource "azurerm_resource_group" "main" {
  name     = "${local.name_prefix}-resources"
  location = "westeurope"
}

# Create Azure AD Application
resource "azuread_application" "main" {
  name = "${local.name_prefix}-principal"
}

# Create Service Principal associated with the Azure AD App
resource "azuread_service_principal" "main" {
  application_id = "${azuread_application.main.application_id}"
}

# Generate random string to be used for service principal password
resource "random_string" "password" {
  length = 32
}

# Create service principal password
resource "azuread_service_principal_password" "main" {
  service_principal_id = "${azuread_service_principal.main.id}"
  value                = "${random_string.password.result}"
  end_date_relative    = "8760h"
}

# Create virtual network (VNet)
resource "azurerm_virtual_network" "main" {
  name                = "${local.name_prefix}-network"
  location            = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"
  address_space       = ["10.240.0.0/16"]
}

# Create AKS subnet to be used by nodes and pods
resource "azurerm_subnet" "aks" {
  name                 = "aks-subnet"
  resource_group_name  = "${azurerm_resource_group.main.name}"
  virtual_network_name = "${azurerm_virtual_network.main.name}"
  address_prefix       = "10.240.1.0/24"
}

# Grant AKS service principal access to join AKS subnet
resource "azurerm_role_assignment" "subnet" {
  scope                = "${azurerm_subnet.aks.id}"
  role_definition_name = "Network Contributor"
  principal_id         = "${azuread_service_principal.main.id}"
}

# Create Kubernetes cluster (AKS)
resource "azurerm_kubernetes_cluster" "main" {
  name                = "${local.name_prefix}-cluster"
  location            = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"
  dns_prefix          = "${local.name_prefix}"
  kubernetes_version  = "1.12.6"

  agent_pool_profile {
    name           = "default"
    count          = "1"
    vm_size        = "Standard_D2s_v3"
    vnet_subnet_id = "${azurerm_subnet.aks.id}"
  }

  network_profile {
    network_plugin = "azure"
  }

  role_based_access_control {
    enabled = true
  }

  service_principal {
    client_id     = "${azuread_application.main.application_id}"
    client_secret = "${azuread_service_principal_password.main.value}"
  }
}
```

</details>

To manage public IP-addresses in another resource group, you can either create a custom role and assign the read and write Public IPs permissions, or just assign the `Network Contributor` role on the resource group.

**Comment by katbyte** [comment]
Thanks for helping everyone out here @joakimhellum-in!

As he has provided a working example i have added it to the example folder in #83 and will close this out once its merged

**Comment by mjiderhamn** [comment]
As for the example by @joakimhellum-in with `azurerm_kubernetes_cluster`, I'd like to add for future reference that for me it didn't work using a `azuread_service_principal_password` as the `service_principal` for `azurerm_kubernetes_cluster`, but I had to use `azuread_application_password`. 

`azuread_application_password`s are what are called _Client secrets_ in the Azure portal, and can be listed with `az ad app credential list`. Running `az ad sp create-for-rbac` creates such _Client secret_.

`azuread_service_principal_password` on the other hand are supposed to be listed with `az ad sp credential list`, but I haven't gotten that to work.

Comparing to the example above, I removed the `azuread_service_principal_password` and replaced with
```
resource "azuread_application_password" "main" {
  # application_id is really object_id. Terraform docs has object_id instead...
  application_id     = "${azuread_application.main.object_id}"
  value              = "${random_string.password.result}"
  end_date_relative  = "8760h"
}
```

And then of course the `azurerm_kubernetes_cluster` will contain
```
  service_principal {
    client_id     = "${azuread_application.main.application_id}"
    client_secret = "${azuread_application_password.main.value}"
  }
```
