### ISSUE TITLE
Release date for 0.2.0?

### ISSUE THREAD

**Issue by erick-thompson** [terraform-providers/terraform-provider-azuread#42]
Is there any estimate on a release date for 0.2.0? I really want to be able to use AD group as a data source, so my terraform files can reference a group by name. I need the group ID/object ID for AKS role assignments. 

Thanks,
Erick

**Comment by katbyte** [comment]
Hi @erick-thompson,

Apologies for the delay, while we were hoping to get `v0.2.0` out this week a unforseen bug in the `v1.220` release of the AzuerRM provider has taken priority as we work to release a bug fix for it. While it may still be release this week it will more likely end up being early next week. 

If you are just doing local work you could always compile the provider locally yourself from master and use that in the meantime (git clone, make build, link $GOPATH/bin/terraform-provider-azurerm to ~/.terraform.d/plugins/darwin_amd64/terraform-provider-azuread on OSX, rm cached provider versions)

**Comment by erick-thompson** [comment]
Excellent, thanks for the update! I can wait until next week, I just wanted to make sure it wasn't months out.

**Comment by erick-thompson** [comment]
Do we have an updated date for this release?

**Comment by katbyte** [comment]
@erick-thompson, 

Upon internal review some additional changes were desired before `v0.2.0` went out and the groups and users schema became final. Some tweaks to both resources have been made in #52 and #57. Once these are merged the  `0.2.0` release will soon follow.

**Comment by gradinDotCom** [comment]
I hit the group up in Gitter, so consider me informed.

**Comment by dominik-lekse** [comment]
I am also looking forward to the release of `v0.2.0`, in particular for the group related resources and data sources.

In my opinion, it would be great to have a release at least every 2 weeks which includes all merged PRs.

**Comment by graham200472** [comment]
I'm another one looking to make use of the changes in v0.2.0.  Looks like [#52](https://github.com/terraform-providers/terraform-provider-azuread/pull/52) and [#57](https://github.com/terraform-providers/terraform-provider-azuread/pull/57) were both merged a few days ago, so does that make the v0.2.0 release imminent?

**Comment by a138076** [comment]
@graham200472 believe the only outstanding item is documentation:
https://github.com/terraform-providers/terraform-provider-azuread/pull/59

**Comment by katbyte** [comment]
@a138076 is correct @graham200472, #59 is the last PR for `v0.2.0`

**Comment by katbyte** [comment]
@a138076, @graham200472, @dominik-lekse, @gradinDotCom, @erick-thompson 

We have just released `v0.2.0` today, thank you for your patience!

**Comment by erick-thompson** [comment]
Thanks for doing this, and keeping us up to date!
