### ISSUE TITLE
Add the behavior of retrieval of an existing azuread_application by appId

### ISSUE THREAD

**Issue by Aadryn** [terraform-providers/terraform-provider-azuread#43]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When referencing an existing azuread_application (data) in terraform script there is only two way to do it. By an **"object_id"**  and **"name"**. Or the main identifier provided by microsoft is the **"appId"**.
I think the usage could be simplier with the use of this property.

### New or Affected Resource(s)
* azuread_application

### Potential Terraform Configuration

```hcl
data "azuread_application" "default"{
  application_id = "the application id to find"
}
```

**Comment by tombuildsstuff** [comment]
hey @Aadryn 

Thanks for opening this issue :)

Given the Application ID is the unique identifier - out of interest what information are you looking to use from the Data Source? Whilst this Data Source originally supported filtering by the Application ID we ultimately removed it since the `name` field didn't appear to be particularly useful on its own vs just hard-coding the ID within the Role Assignment resource?

Thanks!

**Comment by tom-dudley** [comment]
From the [list of attributes](https://github.com/Azure/azure-sdk-for-go/blob/master/services/graphrbac/1.6/graphrbac/models.go#L311-L346) I would say the following would be useful:
- DisplayName
- Homepage
- AppRoles
- AppPermissions
- RequiredResourceAccess
- KeyCredentials

**Comment by Aadryn** [comment]
Hi,
I have a scenario in which i build an AKS cluster with RBAC with an existing azure application. 

I'm using the object_id to find the application but after reflexion i may not need it. But i think in some case for retrieving some properties of the application like identifier_urls / reply_urls for later role assigment in a child application would be useful.
