### ISSUE TITLE
Better handling of azuread_service_principal_password's end_date?

### ISSUE THREAD

**Issue by dekimsey** [terraform-providers/terraform-provider-azuread#45]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, one must set an `end_date` value when using `azuread_service_principal_password`. In the Azure Console, one can select 1 year or 2 years when creating the entry.

I don't see any way (say null resources) to be able to effectively create a relative date to when the resource was created. And (preferably) trigger a refresh at a certain expiry. While I don't know if this is something this module should support. There is something to be said for having a relative date that is only calculated on the initial creation of the resource.

### New or Affected Resource(s)

* azuread_service_principal_password

### Potential Terraform Configuration

```hcl
resource "azuread_service_principal_password" "my-app-secret" {
  service_principal_id = "${azuread_service_principal.my-app.id}"
  value                = "${random_string.consul_sp.result}"
  relative_end_date    = "2yr"
}
```

**Comment by katbyte** [comment]
Thanks for the idea @dekimsey! I like it and hopefully we can get it in at some point.
