### ISSUE TITLE
Group Resource fails if group name contains spaces

### ISSUE THREAD

**Issue by ksix** [terraform-providers/terraform-provider-azuread#48]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.11.11
+ provider.azuread (unversioned) master/83d4ab7

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "test" {
  name = "Test Security Group"
}
```

### Exception Output

Invalid value specified for property 'mailNickname' of resource 'Group'.
{"item":"PropertyName","value":"mailNickname"},
{"item":"PropertyErrorCode","value":"InvalidValue"}

### Expected Behaviour

I would expect to be allowed to create groups with spaces in the name, but currently the provider just passes the exact same value as group name to the mailNickname field, which doesn't support spaces:

```go
properties := graphrbac.GroupCreateParameters{
	DisplayName:     &name,
	MailEnabled:     p.Bool(false), //we're defaulting to false, as the API currently only supports the creation of non-mail enabled security groups.
	MailNickname:    &name,
	SecurityEnabled: p.Bool(true), //we're defaulting to true, as the API currently only supports the creation of non-mail enabled security groups.
}
```

### Actual Behaviour

Failed to create group because having spaces in the mailNickname is unsupported.

### Steps to Reproduce

1. `terraform apply`

### Suggested Fix

Can we just set the MailNickname to a generated GUID instead of the `name` field? That is what the Azure Portal does if creating a non-MailEnabled group from the UI.

**Comment by katbyte** [comment]
Thanks for bringing this to our attention @ksix. That is definitely an oversight and should be fixed, however setting it to a guid is maybe not the ideal solution. What about exposing the main nickname property so while it may default to the name it can be set to something else when spaces are used?

**Comment by ksix** [comment]
@katbyte - that could definitely be a solution. I would argue exposing a field that needs to be set to "something" for technical reasons without providing the end user actual value (until later when you actually support mail enabled groups) is confusing.

I suggested setting a guid, as this is what the Azure portal does when you create a security enabled group which doesn't require the mailNickname field to be set.

I would also continue to set it as a Guid even after this resource supports mail enabled groups, as setting the field to something arbitrary or inconsistent could cause unexpected problems with unique constraints and creates inconsistent data in the group definition, perhaps suggesting the group is mail enabled when it's not?

**Comment by katbyte** [comment]
All good points @ksix, we should definitely follow the portal's example.

I have opened #52 to implement this change, it'll go out with groups in `v0.2.0` 🙂
