### ISSUE TITLE
azuread_application data source returning incorrect application id

### ISSUE THREAD

**Issue by guitmz** [terraform-providers/terraform-provider-azuread#55]
### Affected Resource(s)
- `azuread_application` data source
- `azurerm` provider version is **1.22.1** and `azuread` provider is **0.1.0**

### Terraform Configuration Files
```hcl
data "azuread_application" "client" {
  name = "k8s-auth-client"
}

data "azuread_application" "server" {
  name = "k8s-auth-server"
}

resource "azurerm_kubernetes_cluster" "main" {
...
role_based_access_control {
    enabled = "true"
    azure_active_directory {
      client_app_id     = "${data.azuread_application.client.id}"
      server_app_id     = "${data.azuread_application.server.id}"
      tenant_id         = "${var.arm_tenant_id}"
      server_app_secret = "mycoolsecret"
    }
  }
...
}
```

### Expected Behavior 
Would be the correct application IDs to be returned.

### Actual Behavior
When I run `terraform plan` as usual and I get this in the kubernetes resource:

```
...
role_based_access_control.0.azure_active_directory.0.client_app_id:    "" => "a825ecdb-XXXXXXXXX" (forces new resource)
role_based_access_control.0.azure_active_directory.0.server_app_id:    "" => "4be403f1-XXXXXXXXX" (forces new resource)
...
```

Incorrect IDs are returned. Both returned IDs are not relative to `k8s-auth-client` and `k8s-auth-server` applications. I have no idea what they are and I can't find them anywhere in my account.

**Comment by tiwood** [comment]
I think you have to provide the `id` of the service principal here, no?

Anyway, to get the `application_id` of the application you have to use `application_id` not `id`. `id` contains the object_id of the application.

**Comment by guitmz** [comment]
hey @tiwood, indeed! closing this one, thanks
