### ISSUE TITLE
azuread_application: required_resource_access returning diffs after upgrade to v0.2.0

### ISSUE THREAD

**Issue by tdmalone** [terraform-providers/terraform-provider-azuread#60]
Hi there,

After the upgrade to v0.2.0 we're getting diffs generated for the new `required_resource_access` property on `azuread_application`.

I know we can either:
- pin to v0.1.0; or
- add the existing `required_resource_access` value to our config

but I thought it still worth raising an issue because I think that there's a way to prevent this from happening if the value hasn't been set by Terraform before? (I forget the exact terminology for it though!)

**Comment by katbyte** [comment]
Hi @tdmalone,

I'm sorry to hear you having this issue with 0.2. Could you provide an example config triggering this diff? We have a couple tests without `required_resource_access` set and not seeing any spurious diffs.

**Comment by tdmalone** [comment]
Of course: our config simply specifies the `name`:

```
resource "azuread_application" "terraform_via_bamboo" {
  name = "Terraform via Bamboo"
}

resource "azuread_service_principal" "terraform_via_bamboo" {
  application_id = "${azuread_application.terraform_via_bamboo.application_id}"
}
```

The diffs generated after upgrade look a little like this:

```
build	12-Mar-2019 23:01:42	An execution plan has been generated and is shown below.
build	12-Mar-2019 23:01:42	Resource actions are indicated with the following symbols:
build	12-Mar-2019 23:01:42	  ~ update in-place
build	12-Mar-2019 23:01:42	
build	12-Mar-2019 23:01:42	Terraform will perform the following actions:
build	12-Mar-2019 23:01:42	
build	12-Mar-2019 23:01:42	~ azuread_application.terraform_via_bamboo
build	12-Mar-2019 23:01:42	      required_resource_access.#:                               "1" => "0"
build	12-Mar-2019 23:01:42	      required_resource_access.55917893.resource_access.#:      "1" => "0"
build	12-Mar-2019 23:01:42	      required_resource_access.55917893.resource_access.0.id:   "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" => ""
build	12-Mar-2019 23:01:42	      required_resource_access.55917893.resource_access.0.type: "Role" => ""
build	12-Mar-2019 23:01:42	      required_resource_access.55917893.resource_app_id:        "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" => ""
build	12-Mar-2019 23:01:42	Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by katbyte** [comment]
That's interesting, we have [an acceptance test](https://github.com/terraform-providers/terraform-provider-azuread/blob/eb6712365dc9342ab3b8a8e262cf2fe0ffc08b71/azuread/resource_application_test.go#L182) that does the exact same and passes.

As you mentioned they are imported it sounds like a bug in the import code.

**Comment by tdmalone** [comment]
I _think_ they were originally created in Azure and then imported but I could be wrong - we may have created them via Terraform in the first place.

Anyway - not a big issue for us, we can work around it; I just thought it worth mentioning in case something was missed in the addition of the new property. But it sounds like it wasn't, so perhaps it's just a difficult-to-reproduce edge case!

**Comment by katbyte** [comment]
Looked into this a bit more and it appears the portal automatically assigns some default required resources access values. As such i am going to close this.
