### ISSUE TITLE
azuread_service_principal: error 403, tries to create multi-tenant application

### ISSUE THREAD

**Issue by mion00** [terraform-providers/terraform-provider-azuread#65]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.11.13
+ provider.azuread v0.2.0
+ provider.random v2.1.0

### Affected Resource(s)

* `azuread_service_principal`

### Terraform Configuration Files

```hcl

# Configure the Microsoft Azure Active Directory Provider
provider "azuread" {
  version = "~> 0.2.0"
}

resource "azuread_application" "test-reference" {
  name = "test"
  available_to_other_tenants = false
}

resource "azuread_service_principal" "test-service-principal" {
  application_id = "${azuread_application.test-reference.id}"
}

resource "random_string" "service-principal-password" {
  length  = 16
  special = true

  keepers = {
    # Generate a new password each time we switch to a new service principal
    service_principal_id = "${azuread_service_principal.test-service-principal.id}"
  }
}

resource "azuread_service_principal_password" "service-principal-password" {
  service_principal_id = "${azuread_service_principal.test-service-principal.id}"
  value                = "${random_string.service-principal-password.result}"
  end_date             = "2020-01-01T00:00:00Z"
}

```

### Debug Output
https://gist.github.com/mion00/ae046421c2c11aba6dd3b7d825b14833

### Expected Behavior

Terraform should have created an application, a service principal and set the given random password to the service principal.

### Actual Behavior
 Terraform creates the application, but fails in creating the service principal.

The error is:

```
* azuread_service_principal.test-service-principal: Error creating Service Principal for application  "48b74525-6738-4857-b3a5-d9ae29309526": graphrbac.ServicePrincipalsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authentication_Unauthorized","date":"2019-03-22T11:12:02","message":{"lang":"en","value":"Authenticating principal does not havepermission to instantiate multi-tenantapplications and there is not matching Applicationin the request tenant."},"requestId":"cfcf67f3-6d8c-42f5-b5e2-782e4b971b3a"}}]
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
None

### References

Seems similar to  #35, but I am using the `az CLI` for authentication, not a Service Principal

**Comment by tiwood** [comment]
You have to use the application_id of the application, but it seems you've used the object id.

Please try

```hcl
resource "azuread_service_principal" "test-service-principal" {
  application_id = "${azuread_application.test-reference.application_id}"
}
```
instead of
```hcl
resource "azuread_service_principal" "test-service-principal" {
  application_id = "${azuread_application.test-reference.id}"
}
```

**Comment by mion00** [comment]
Damn I missed that detail! Sorry for the bother.
