### ISSUE TITLE
Add ability to manage custom RBAC roles

### ISSUE THREAD

**Issue by erick-thompson** [terraform-providers/terraform-provider-azuread#69]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

It would be very helpful to have a way in this provider to manage custom RBAC roles. We are moving towards using AAD PIM to manage permissions (as opposed to direct group memberships), so we will be creating a number of custom roles. Some examples:

1. AKS Administration
2. Application Gateway Configuration Editor
3. Application Deployment Operator

### References

* https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-resource-roles-custom-role-policy
* https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-roles

**Comment by katbyte** [comment]
Hi @erick-thompson,

It looks like you opened this right after #68. As this is a duplicate i am going to close it in favour od that issue.

**Comment by erick-thompson** [comment]
This issue is different than #68. This item is about managing RBAC roles, while the #69 is about configuring PIM.

**Comment by katbyte** [comment]
Thanks for clarifying, reopening!

**Comment by manicminer** [comment]
Hi @erick-thompson, thanks for opening this. Do I understand correctly that this is about [custom RBAC roles](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles) for access to Azure resources? If so, it looks like this should belong in the [AzureRM provider](https://github.com/terraform-providers/terraform-provider-azurerm).

**Comment by erick-thompson** [comment]
I think you are correct, thanks!
