### ISSUE TITLE
azuread_application: Add support for custom app roles

### ISSUE THREAD

**Issue by aj-devops-wi** [terraform-providers/terraform-provider-azuread#75]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is slightly different than the existing requests (that I can see).  This request is for the ability to add custom app roles to an Azure AD App Registration.  This can be done programmatically via PowerShell currently, it would be great to have Terraform support.

### New or Affected Resource(s)

* azuread_application
* azuread_application_group_role
* azuread_application_user_role

### Potential Terraform Configuration

```hcl
data "azuread_application_group_role" "myCustomGroupRole" {
    name = "myCustomRole"
    azureADGroupName = "MyAzureADGroupName"
    }

data "azuread_application_user_role "myCustomUserRole" {
    name = "myCustomUserRole"
    azureADUserName = "user1@mydomain.com"
}

resource "azuread_application" "test_registration" {
    name                       = "${var.azuread_appname}"
    homepage                   = "${var.azuread_homepage}"
    identifier_uris            = "${var.azuread_identifier_uris}"
    reply_urls                 = "${var.azuread_reply_urls}"
    available_to_other_tenants = "${var.azuread_available_to_other_tenants}"
    oauth2_allow_implicit_flow = "${var.azuread_oauth2_allow_implicit_flow}"
    approles                   = ["${data.azuread_application_group_role.myCustomGroupRole}, ${data.azuread_application_group_role.myCustomUserRole}]
}

```

### References

https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadgroupapproleassignment?view=azureadps-2.0
https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureaduserapproleassignment?view=azureadps-2.0
https://docs.microsoft.com/en-us/powershell/module/azuread/set-azureadapplication?view=azureadps-2.0

* #0000

**Comment by danstis** [comment]
This should also include the possibility to create an 'application' role. Potentially `azuread_application_application_role`
For example in PowerShell: 
`New-AzureADApplicationRole -Name "Application.Access" -Description "Allows application access" -AllowedMemberTypes "Application"`
