### ISSUE TITLE
azuread_service_principal_password: detect upcoming expiry and re-create resource

### ISSUE THREAD

**Issue by StephenWithPH** [terraform-providers/terraform-provider-azuread#80]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azuread_service_principal_password` allows users to set a password expiration. The resource does not provide a way for Terraform users to smooth workflows around password expiry. Inspired by https://www.terraform.io/docs/providers/acme/r/certificate.html#min_days_remaining, a nice feature would allow users to set a lead time before password expiry where Terraform will automatically delete and re-create the resource. See the [ACME provider code](https://github.com/terraform-providers/terraform-provider-acme/blob/eee906efd24140ff2349d6174cd272d545d1ae7b/acme/resource_acme_certificate.go#L83-L109) for a more concrete example of how the certificate resources handles auto-magic detection of the need to re-create the resource.

### New or Affected Resource(s)

* azuread_service_principal_password

### Potential Terraform Configuration

```hcl
resource "azuread_application" "test" {
  name                       = "example"
  homepage                   = "http://homepage"
  identifier_uris            = ["http://uri"]
  reply_urls                 = ["http://replyurl"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = true
}

resource "azuread_service_principal" "test" {
  application_id = "${azuread_application.test.application_id}"
}

resource "azuread_service_principal_password" "test" {
  service_principal_id = "${azuread_service_principal.test.id}"
  value                = "VT=uSgbTanZhyz@%nL9Hpd+Tfay_MRV#"
  end_date_relative    = "240h"
  min_days_remaining   = 5 # this is the new field
}

```

**Comment by katbyte** [comment]
Also would be good to add to application password resource once that resource is in

**Comment by manicminer** [comment]
Hi @StephenWithPH, thanks for requesting this feature. I know that password rotation can be a pain point.

Expiring or rotating password only seems to make sense to me, if the value is also changed at the same time. Unfortunately given that these isn't a way to uniformly effect a new value - since it's user-specified and could come from anywhere - I don't that feel auto-renewal would be a useful addition right now. It would likely encourage password reuse, effectively extending password expiry forever.

**Comment by StephenWithPH** [comment]
> I don't that feel auto-renewal would be a useful addition right now. It would likely encourage password reuse, effectively extending password expiry forever.

That's a valid point. Does Azure itself allow password reuse in the case? If the answer is "yes", then I believe that it's not the Terraform provider's role to enforce a higher standard of behavior.

I'm no longer actively working with Azure; were there no :+1: on this, I would close it. Given that there are 12, I'll leave this open so the upvoters have time to weigh in.

**Comment by manicminer** [comment]
@StephenWithPH thanks for taking the time to reply. The portal UI doesn't allow re-use; it generates a random string for you with no opportunity to submit your own. The CLI does/did something similar. I'm not sure about the Powershell modules.

I'm going to close this issue. I've thought about this some more, and given that this resource accepts a user supplied password/secret value, I think it's out of scope for this resource to rotate or extend the validity. A new value should simply be supplied.

Thanks again for replying.

**Comment by manicminer** [comment]
With the help of some colleagues, I've found a way to rotate passwords using existing resource features, in case this helps anyone.

```hcl
provider "azuread" {}

resource "azuread_application" "test" {
  name = "example-site3"
}

resource "azuread_service_principal" "test" {
  application_id = azuread_application.test.application_id
}

resource "time_rotating" "test" {
  rotation_days = 30
}

resource "random_password" "test" {
  length  = 32
  special = false
  keepers = {
    expiry = time_rotating.test.rotation_rfc3339
  }
}

resource "azuread_application_password" "test" {
  application_object_id = azuread_application.test.id
  value                 = random_password.test.result
  end_date              = time_rotating.test.rotation_rfc3339
}


```
