### ISSUE TITLE
groupMembershipClaims is missing from azuread_application

### ISSUE THREAD

**Issue by jdfalk** [terraform-providers/terraform-provider-azuread#92]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azuread_application should have an option to set the groupMembershipClaims field

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```hcl
# Default
resource "azuread_application" "testdefault" {
  name                       = "testapp"
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
  group_membership_claims    = null 

# configured
resource "azuread_application" "testconfigured" {
  name                       = "testapp"
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
  group_membership_claims    = "All" 
```

### References

https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration-cli#create-azure-ad-server-component this is creating the applications and service principals for AKS -> AZ AD Auth

* #0000

**Comment by katbyte** [comment]
Hi @jdfalk,

The provider currently does support this! The website just hasn't been updated in a couple releases so thank you very much for the issue. Just deploying it now so it [should appear shortly](https://www.terraform.io/docs/providers/azuread/r/application.html)
